# 03 Backtest Performance: V2 Portfolio Backtest

## Purpose

This notebook runs the V2 portfolio-level statistical arbitrage backtest.

Unlike the archived V1 notebook, which evaluated a single selected pair in-sample, this notebook evaluates portfolios of selected pairs across walk-forward folds. The objective is to transform fold-level selected pair outputs into portfolio-level return streams, using multiple weighting methods and transaction cost assumptions.

The outputs from this notebook are saved as structured artifacts and passed into Notebook 04 for research interpretation, visualization, and final reporting.

## V2 Scope

This notebook covers:

- loading V2 walk-forward/OOS artifacts
- loading selected pairs per training fold
- constructing portfolio weights
- running pair-level or portfolio-level backtests per fold
- aggregating weighted pair returns into portfolio returns
- computing core portfolio performance metrics
- saving clean CSV/JSON outputs for Notebook 04

This notebook does not focus on final research storytelling. Interpretation, comparisons, charts, and README-facing conclusions are handled in Notebook 04.

## 1. Setup And Imports

This section loads Python libraries, project paths, and project modules required for the V2 portfolio backtest.

Expected modules include:

- configuration loaders
- pair backtest logic
- portfolio weighting functions
- cost model utilities
- performance metric functions

In [1]:
import sys
from pathlib import Path
import pandas as pd
import numpy as np
import os
import glob
import pickle
import json
import re

PROJECT_ROOT = Path.cwd()

if PROJECT_ROOT.name == 'notebooks':
    PROJECT_ROOT = PROJECT_ROOT.parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

from src.spread_model import (
    compute_log_prices,
    estimate_hedge_model, 
    compute_spread, 
    compute_zscore
)
from src.cost_model import (
    estimate_total_pair_cost_bps,
    bps_to_decimal
)
from src.portfolio import (
    equal_weight,
    rank_weight,
    inverse_half_life,
    validate_portfolio_weights_by_fold
)
from src.config_loader import (
    load_universe_config,
    load_run_config,
    load_metrics_config
)

from src.backtest import run_pair_backtest

from src.metrics import summarize_portfolio_by_fold

print(f"Project root: {PROJECT_ROOT}")
print("Notebook 03 imports loaded successfully.")

Project root: c:\Users\Aditi\Aditi_Workspaces\VSCode\QuantProjects\pairs-trading-ai-tech
Notebook 03 imports loaded successfully.

## 2. Define Paths And Output Locations

This section defines the input and output folders used by the V2 portfolio backtest.

Notebook 03 reads cached artifacts from prior notebooks and writes portfolio-level outputs to dedicated V2 output folders.

In [2]:
OUTPUT_DIR = PROJECT_ROOT / "outputs"
TABLES_DIR = OUTPUT_DIR / "tables"
FIGURES_DIR = OUTPUT_DIR / "figures"
CONFIG_DIR = PROJECT_ROOT / "config"

V2_BACKTEST_DIR = OUTPUT_DIR / "v2_portfolio_backtest"
V2_TABLES_DIR = V2_BACKTEST_DIR / "tables"
V2_OBJECTS_DIR = V2_BACKTEST_DIR / "objects"
V2_FIGURES_DIR = V2_BACKTEST_DIR / "figures"

for directory in [
    OUTPUT_DIR,
    TABLES_DIR,
    FIGURES_DIR,
    V2_BACKTEST_DIR,
    V2_TABLES_DIR,
    V2_FIGURES_DIR,
]:
    directory.mkdir(parents=True, exist_ok=True)

print("Project root:", PROJECT_ROOT)
print("Output dir:", OUTPUT_DIR)
print("V2 backtest dir:", V2_BACKTEST_DIR)

Project root: c:\Users\Aditi\Aditi_Workspaces\VSCode\QuantProjects\pairs-trading-ai-tech
Output dir: c:\Users\Aditi\Aditi_Workspaces\VSCode\QuantProjects\pairs-trading-ai-tech\outputs
V2 backtest dir: c:\Users\Aditi\Aditi_Workspaces\VSCode\QuantProjects\pairs-trading-ai-tech\outputs\v2_portfolio_backtest

## 3. Load Configuration Files

This section loads the run configuration, metrics configuration, universe configuration, and any V2 cost or portfolio settings.

The configuration layer is used to avoid hardcoding dates, thresholds, file names, and assumptions inside the notebook.

### Files required: 

 - `config/v2_metrics.json`
 - `config/v2_universe.json`
 - `config/run_config.json`
 - `outputs/v2_portfolio_backtest/tables/fold_1_selected_pairs.csv`
 - `outputs/v2_portfolio_backtest/tables/fold_1_oos_prices.csv`
 - `outputs/v2_portfolio_backtest/tables/fold_1_oos_dollar_volume.csv`
 - `outputs/v2_portfolio_backtest/tables/fold_1_test_prices.csv`
 - `outputs/v2_portfolio_backtest/tables/fold_1_test_dollar_volume.csv`
 - `outputs/v2_portfolio_backtest/tables/fold_1_train_prices.csv`
 - `outputs/v2_portfolio_backtest/tables/fold_2_selected_pairs.csv`
 - `outputs/v2_portfolio_backtest/tables/fold_2_oos_prices.csv`
 - `outputs/v2_portfolio_backtest/tables/fold_2_oos_dollar_volume.csv`
 - `outputs/v2_portfolio_backtest/tables/fold_2_test_prices.csv`
 - `outputs/v2_portfolio_backtest/tables/fold_2_test_dollar_volume.csv`
 - `outputs/v2_portfolio_backtest/tables/fold_2_train_prices.csv`
 - `outputs/v2_portfolio_backtest/tables/fold_3_selected_pairs.csv`
 - `outputs/v2_portfolio_backtest/tables/fold_3_oos_prices.csv`
 - `outputs/v2_portfolio_backtest/tables/fold_3_oos_dollar_volume.csv`
 - `outputs/v2_portfolio_backtest/tables/fold_3_test_prices.csv`
 - `outputs/v2_portfolio_backtest/tables/fold_3_test_dollar_volume.csv`
 - `outputs/v2_portfolio_backtest/tables/fold_3_train_prices.csv`
 - `outputs/v2_portfolio_backtest/objects/v2_fold_pair_model_artifacts.pkl`
 - `outputs/v2_portfolio_backtest/objects/v2_fold_pair_model_metadata.json`

In [3]:
run_config_file_path = PROJECT_ROOT/"config/run_config.json"
metric_config_file_path = PROJECT_ROOT/"config/v2_metrics.json"

with open(run_config_file_path,'r') as file:
    config = json.load(file)

with open(metric_config_file_path,'r') as file:
    metric_config = json.load(file)

## 4. Load V2 Walk-Forward Artifacts

This section loads the outputs produced by Notebook 02.

Expected artifacts may include:

- selected pairs by fold
- hedge models by fold/pair
- spread series by fold/pair
- z-score series by fold/pair
- train/test fold metadata
- pair ranking summaries

The goal is to reconstruct the full set of inputs needed for portfolio-level backtesting.

### 4.1 Define Selected Pair File Paths

Selected pair outputs are stored by fold under the project output directory. The filenames  contain fold identifiers so that each selected pair table can be matched to its corresponding test-period price data.

In [4]:
SELECTED_PAIR_DIR = V2_TABLES_DIR
naming_pattern = "*_selected_pairs.csv"
search_path = os.path.join(SELECTED_PAIR_DIR, naming_pattern)
csv_files = glob.glob(search_path)
print(csv_files, len(csv_files))

['c:\\Users\\Aditi\\Aditi_Workspaces\\VSCode\\QuantProjects\\pairs-trading-ai-tech\\outputs\\v2_portfolio_backtest\\tables\\fold_1_selected_pairs.csv', 'c:\\Users\\Aditi\\Aditi_Workspaces\\VSCode\\QuantProjects\\pairs-trading-ai-tech\\outputs\\v2_portfolio_backtest\\tables\\fold_2_selected_pairs.csv', 'c:\\Users\\Aditi\\Aditi_Workspaces\\VSCode\\QuantProjects\\pairs-trading-ai-tech\\outputs\\v2_portfolio_backtest\\tables\\fold_3_selected_pairs.csv'] 3

### 4.2 Parse Fold Identifiers

This subsection extracts fold identifiers from selected-pair filenames. The fold identifier is used as the key for matching selected pairs to test and OOS price data in later sections.

### 4.3 Load Selected Pair Tables

This subsection loads each selected-pair CSV into a dictionary keyed by fold ID. These selected pairs are training-derived and will later be used to construct portfolio weights.

In [5]:
selected_pairs_by_fold = {}

for file in csv_files:
    
    file = Path(file)
    match = re.search(r"(fold_\d+)",file.stem)
    
    if match is None:
        raise ValueError(f"Could not parse fold id from file name: {file.name}")

    fold_id = match.group(1)
    selected_pairs_by_fold[fold_id] = pd.read_csv(file)

### 4.4 Inspect Loaded Selected Pair Tables

This subsection performs a light inspection of the loaded selected-pair tables to confirm that the expected folds and columns are present.

In [6]:
print("\nDictionary keys:", selected_pairs_by_fold.keys())
first_element = selected_pairs_by_fold["fold_1"]
print("\nFirst element sample:", first_element.head())
print("\nFirst element columns:", first_element.columns)
print("\nFirst element dimension:", first_element.shape)

Dictionary keys: dict_keys(['fold_1', 'fold_2', 'fold_3'])

First element sample:   asset_y asset_x  correlation  cointegration_pvalue  cointegration_passed  \
0     PEP    COST     0.622783              0.000248                  True
1     UNP    AVGO     0.614099              0.000360                  True
2   CMCSA     HON     0.583763              0.000571                  True
3   BRK-B      PM     0.630418              0.001012                  True
4     JNJ    ABBV     0.456989              0.002040                  True

   half_life  liquidity_passed  avg_dollar_volume_y  avg_dollar_volume_x  rank
0   9.566572              True         5.342328e+08         7.227777e+08     1
1   9.769209              True         5.174857e+08         7.066761e+08     2
2  10.033131              True         7.297389e+08         4.687945e+08     3
3  17.274298              True         1.098229e+09         3.200314e+08     4
4  13.286042              True         9.272477e+08         5.844794e+08     5

First element columns: Index(['asset_y', 'asset_x', 'correlation', 'cointegration_pvalue',
       'cointegration_passed', 'half_life', 'liquidity_passed',
       'avg_dollar_volume_y', 'avg_dollar_volume_x', 'rank'],
      dtype='str')

First element dimension: (50, 10)

### 4.5 Section Summary

The selected-pair CSV files have been loaded into a fold-keyed dictionary. These tables will be used in later sections to calculate portfolio weights before running test and OOS backtests.

## 5. Load Test And OOS Price Data By Fold

This section loads the price data required to evaluate the selected pairs.

The selected pair tables were generated from training windows. In this section, the corresponding test-period and final OOS price data are loaded separately so that portfolio performance can be evaluated without using future information during pair selection or portfolio weighting.

The key outputs of this section are:

- test price data by fold
- final OOS price data, if available
- fold identifiers that can be matched against the selected-pair dictionary

### 5.1 Fetching Test prices and OOS prices filepaths

In [7]:
test_prices_by_fold = {}
oos_prices_by_fold = {}

test_naming_pattern = "*_test_prices.csv"
test_search_path = os.path.join(SELECTED_PAIR_DIR, test_naming_pattern)
test_file_paths = glob.glob(test_search_path)

oos_naming_pattern = "*_oos_prices.csv"
oos_search_path = os.path.join(SELECTED_PAIR_DIR, oos_naming_pattern)
oos_file_paths = glob.glob(oos_search_path)

print("\nTest price filepaths and size:", test_file_paths, len(test_file_paths))
print("\nOOS price filepaths and size:", oos_file_paths, len(oos_file_paths))

Test price filepaths and size: ['c:\\Users\\Aditi\\Aditi_Workspaces\\VSCode\\QuantProjects\\pairs-trading-ai-tech\\outputs\\v2_portfolio_backtest\\tables\\fold_1_test_prices.csv', 'c:\\Users\\Aditi\\Aditi_Workspaces\\VSCode\\QuantProjects\\pairs-trading-ai-tech\\outputs\\v2_portfolio_backtest\\tables\\fold_2_test_prices.csv', 'c:\\Users\\Aditi\\Aditi_Workspaces\\VSCode\\QuantProjects\\pairs-trading-ai-tech\\outputs\\v2_portfolio_backtest\\tables\\fold_3_test_prices.csv'] 3

OOS price filepaths and size: ['c:\\Users\\Aditi\\Aditi_Workspaces\\VSCode\\QuantProjects\\pairs-trading-ai-tech\\outputs\\v2_portfolio_backtest\\tables\\fold_1_oos_prices.csv', 'c:\\Users\\Aditi\\Aditi_Workspaces\\VSCode\\QuantProjects\\pairs-trading-ai-tech\\outputs\\v2_portfolio_backtest\\tables\\fold_2_oos_prices.csv', 'c:\\Users\\Aditi\\Aditi_Workspaces\\VSCode\\QuantProjects\\pairs-trading-ai-tech\\outputs\\v2_portfolio_backtest\\tables\\fold_3_oos_prices.csv'] 3

### 5.2 Parse Fold Identifiers

This subsection extracts fold identifiers from test prices and OOS prices filenames.

### 5.3 Load Test Price and OOS Price Tables

This subsection loads each test_price and each oos_price CSV into a respective dictionary keyed by fold ID. These price tables will be used to check the performnace of teh pairs strategy.

In [8]:
for file_path in test_file_paths:
    
    file = Path(file_path)
    match = re.search(r"(fold_\d+)",file.stem)
    
    if match is None:
        raise ValueError(f"Could not parse fold id from file name: {file.name}")

    fold_id = match.group(1)
    test_prices_by_fold[fold_id] = pd.read_csv(file,index_col='date',parse_dates=True)

In [9]:
for file_path in oos_file_paths:
    
    file = Path(file_path)
    match = re.search(r"(fold_\d+)",file.stem)
    
    if match is None:
        raise ValueError(f"Could not parse fold id from file name: {file.name}")

    fold_id = match.group(1)
    oos_prices_by_fold[fold_id] = pd.read_csv(file,index_col='date',parse_dates=True)

### 5.4 Inspect Loaded Test Price and OOS Price Tables

This subsection performs a light inspection of the loaded test price and OOS price tables to confirm that the expected folds and columns are present.

In [10]:
#For test data
sample_df = test_prices_by_fold["fold_1"]
print("\n Sample df index:",sample_df.index)
print("\n Sample df index type:", type(sample_df.index))
print("\n IS the index increasing: ",sample_df.index.is_monotonic_increasing)
print("\n Sample df index is duplicated check:",sum(sample_df.index.duplicated()))
print("\n Sample df dimensions:",sample_df.shape)
print("\n First 10 columns:",sample_df.columns[:10])

 Sample df index: DatetimeIndex(['2022-01-03 00:00:00+00:00', '2022-01-04 00:00:00+00:00',
               '2022-01-05 00:00:00+00:00', '2022-01-06 00:00:00+00:00',
               '2022-01-07 00:00:00+00:00', '2022-01-10 00:00:00+00:00',
               '2022-01-11 00:00:00+00:00', '2022-01-12 00:00:00+00:00',
               '2022-01-13 00:00:00+00:00', '2022-01-14 00:00:00+00:00',
               ...
               '2022-12-16 00:00:00+00:00', '2022-12-19 00:00:00+00:00',
               '2022-12-20 00:00:00+00:00', '2022-12-21 00:00:00+00:00',
               '2022-12-22 00:00:00+00:00', '2022-12-23 00:00:00+00:00',
               '2022-12-27 00:00:00+00:00', '2022-12-28 00:00:00+00:00',
               '2022-12-29 00:00:00+00:00', '2022-12-30 00:00:00+00:00'],
              dtype='datetime64[us, UTC]', name='date', length=251, freq=None)

 Sample df index type: <class 'pandas.DatetimeIndex'>

 IS the index increasing:  True

 Sample df index is duplicated check: 0

 Sample df dimensions: (251, 50)

 First 10 columns: Index(['MSFT', 'AAPL', 'AMZN', 'GOOGL', 'BRK-B', 'META', 'JNJ', 'JPM', 'V',
       'XOM'],
      dtype='str')

In [11]:
#For OOS data
sample_df = oos_prices_by_fold["fold_1"]
print("\n Sample df index:",sample_df.index)
print("\n Sample df index type:", type(sample_df.index[0]))
print("\n IS the index increasing: ",sample_df.index.is_monotonic_increasing)
print("\n Sample df index is duplicated check:",sum(sample_df.index.duplicated()))
print("\n Sample df dimensions:",sample_df.shape)
print("\n First 10 columns:",sample_df.columns[:10])

 Sample df index: DatetimeIndex(['2023-01-03 00:00:00+00:00', '2023-01-04 00:00:00+00:00',
               '2023-01-05 00:00:00+00:00', '2023-01-06 00:00:00+00:00',
               '2023-01-09 00:00:00+00:00', '2023-01-10 00:00:00+00:00',
               '2023-01-11 00:00:00+00:00', '2023-01-12 00:00:00+00:00',
               '2023-01-13 00:00:00+00:00', '2023-01-17 00:00:00+00:00',
               ...
               '2023-12-15 00:00:00+00:00', '2023-12-18 00:00:00+00:00',
               '2023-12-19 00:00:00+00:00', '2023-12-20 00:00:00+00:00',
               '2023-12-21 00:00:00+00:00', '2023-12-22 00:00:00+00:00',
               '2023-12-26 00:00:00+00:00', '2023-12-27 00:00:00+00:00',
               '2023-12-28 00:00:00+00:00', '2023-12-29 00:00:00+00:00'],
              dtype='datetime64[us, UTC]', name='date', length=250, freq=None)

 Sample df index type: <class 'pandas.Timestamp'>

 IS the index increasing:  True

 Sample df index is duplicated check: 0

 Sample df dimensions: (250, 50)

 First 10 columns: Index(['MSFT', 'AAPL', 'AMZN', 'GOOGL', 'BRK-B', 'META', 'JNJ', 'JPM', 'V',
       'XOM'],
      dtype='str')

## 6. Validate Fold Alignment And Loaded Artifacts

This section performs sanity checks before portfolio construction and backtesting.

Checks include:

- selected pair tables are non-empty
- fold identifiers are present
- required ranking/weighting columns exist
- test price data exists for each selected-pair fold
- final OOS price data is loaded separately
- selected pair tickers exist in the corresponding price matrices
- date indices are parsed correctly and sorted

These checks prevent silent errors before the portfolio backtest loop.

In [12]:
#Check 1: The same folds are presented in selected_pairs_by_fold and test_prices_by fold
print("\nSelected pairs and test prices folds match:",selected_pairs_by_fold.keys() == test_prices_by_fold.keys())

Selected pairs and test prices folds match: True

In [13]:
#Check 2: Every selected pair ticker must exist in that fold's price_matrix.
missing_tickers_by_fold = {}

for fold_id in selected_pairs_by_fold:
    selected_pairs_df = selected_pairs_by_fold[fold_id]
    price_df = test_prices_by_fold[fold_id]
    
    selected_tickers = set(selected_pairs_df["asset_y"]).union(set(selected_pairs_df["asset_x"]))
    price_tickers = set(price_df.columns)
    
    missing_tickers = selected_tickers - price_tickers
    
    if missing_tickers:
        missing_tickers_by_fold[fold_id] = sorted(missing_tickers)
        print("Missing tickers by fold:", missing_tickers)
    
if missing_tickers_by_fold:
    raise ValueError(f"Missing tickers in test price data:{missing_tickers_by_fold}")
print("All selected-pair tickers are present in corresponding fold price matrices.")

All selected-pair tickers are present in corresponding fold price matrices.

In [14]:
#Check 3: no empty DataFrames
empty_selected_pair_folds = []
empty_test_price_folds = []

for fold_id, selected_pairs_df in selected_pairs_by_fold.items():
    if selected_pairs_df.empty:
        empty_selected_pair_folds.append(fold_id)

for fold_id, test_prices_df in test_prices_by_fold.items():
    if test_prices_df.empty:
        empty_test_price_folds.append(fold_id)

print("Empty selected-pair folds:",empty_selected_pair_folds)
print("Empty test-price folds:",empty_test_price_folds)

if empty_selected_pair_folds:
    raise ValueError(f"Empty DataFrame present in {empty_selected_pair_folds}")
if empty_test_price_folds:
    raise ValueError(f"Empty DataFrame present in {empty_test_price_folds}")
print("All DataFrames for selected pairs and test prices are not empty.")

Empty selected-pair folds: []
Empty test-price folds: []
All DataFrames for selected pairs and test prices are not empty.

In [15]:
#Check 4: OOS Price DataFrames are valid
for fold_id, oos_prices_df in oos_prices_by_fold.items():
    print(f"\n For {fold_id}:")
    print(type(oos_prices_df))
    print(oos_prices_df.shape)
    print(oos_prices_df.index.is_monotonic_increasing)
    print(oos_prices_df.index.duplicated().sum())
    print(oos_prices_df.index.min(), oos_prices_df.index.max())

 For fold_1:
<class 'pandas.DataFrame'>
(250, 50)
True
0
2023-01-03 00:00:00+00:00 2023-12-29 00:00:00+00:00

 For fold_2:
<class 'pandas.DataFrame'>
(252, 50)
True
0
2024-01-02 00:00:00+00:00 2024-12-31 00:00:00+00:00

 For fold_3:
<class 'pandas.DataFrame'>
(250, 50)
True
0
2025-01-02 00:00:00+00:00 2025-12-31 00:00:00+00:00

## 7. Define Portfolio Weighting Methods

This section defines which portfolio weighting methods will be evaluated.

Candidate V2 weighting methods include:

- equal weight
- rank-based weight
- inverse half-life weight
- signal-strength weight, if available
- liquidity-aware weight, if implemented

Each method converts a selected-pair table into a normalized weight vector.

### 7.1 Loading Fold Pair Artifacts and Metadata

The artifacts are present in a pickle file, which is used to store data objects in Python. The
pickle file contains the hedge model, spread and z-score calculated for every selected pair
in each fold. The metadata is stored as a json file. In this subsection, these files will be loaded into the notebook.

In [16]:
artifact_file_path = V2_OBJECTS_DIR/"v2_fold_pair_model_artifacts.pkl"
metadata_file_path = V2_OBJECTS_DIR/"v2_fold_pair_model_metadata.json"

with open(artifact_file_path,'rb') as file:
    artifact = pickle.load(file)

print(artifact.keys())
print(artifact['fold_1'].keys())

with open(metadata_file_path,'r') as file:
    metadata = json.load(file)

dict_keys(['fold_1', 'fold_2', 'fold_3'])
dict_keys(['selected_pairs', 'hedge_models_by_pair', 'spreads_by_pair', 'zscores_by_pair', 'spread_params_by_pair'])

In [17]:
for fold_id in selected_pairs_by_fold: 
    csv_pairs = selected_pairs_by_fold[fold_id]
    artifact_pairs = artifact[fold_id]["selected_pairs"]
    print(fold_id, csv_pairs.shape, artifact_pairs.shape)

fold_1 (50, 10) (50, 10)
fold_2 (50, 10) (50, 10)
fold_3 (24, 10) (24, 10)

## 8. Construct Portfolio Weights By Fold

This section applies each weighting method to the selected pairs in each walk-forward fold.

The output is a structured table containing:

- fold ID
- pair name
- weighting method
- portfolio weight
- ranking/diagnostic columns used to calculate the weight

These weights are later used to aggregate pair-level strategy returns into portfolio-level returns.

### 8.1 Define Weighting Methods

This subsection defines the portfolio weighting methods evaluated in the V2 backtest.

Each weighting method takes a selected-pair DataFrame for a given fold and returns a normalized weight vector. The methods are stored in a dictionary so that the same construction loop can be applied across all folds and weighting schemes.

Only tested weighting methods are included in this V2 notebook.

In [18]:
WEIGHTING_METHODS = {
    "equal_weight": lambda df: equal_weight(
        df,
        required_cols=["asset_y", "asset_x"],
    ),
    "rank_weight": lambda df: rank_weight(
        df,
        rank_col="rank",
    ),
    "inverse_half_life": lambda df: inverse_half_life(
        df
        
    )
}

print("Weighting methods:")
for method_name in WEIGHTING_METHODS:
    print("-", method_name)

Weighting methods:
- equal_weight
- rank_weight
- inverse_half_life

### 8.2 Prepare Selected Pair Tables For Weighting

This subsection prepares the fold-level selected pair tables for portfolio weight construction.

Each selected-pair table is copied into a working dictionary and assigned a stable `pair_key` using the pair convention:

`asset_y_asset_x`

This key must match the pair keys stored in the fold-level model artifacts, because later sections will use the same key to connect portfolio weights, hedge models, spreads, z-scores, and test-period price data.

In [19]:
selected_pairs_for_weights_by_fold = {}

required_pair_cols = ["asset_y","asset_x"]

for fold_id, selected_pairs_df in selected_pairs_by_fold.items():
    missing_cols = set(required_pair_cols) - set(selected_pairs_df.columns)
    
    if missing_cols:
        raise ValueError(
            f"{fold_id} selected pairs missing required columns: {missing_cols}"
        )

    weights_input_df = selected_pairs_df.copy()
    
    weights_input_df["pair_key"] = (
        weights_input_df["asset_y"].astype(str)
        + "_"
        + weights_input_df["asset_x"].astype(str)
    )
    
    if weights_input_df["pair_key"].isna().any():
        raise ValueError(f"{fold_id} contains null pair keys.")
    
    if weights_input_df["pair_key"].duplicated().any():
        duplicate_pairs = (
            weights_input_df.loc[
                weights_input_df["pair_key"].duplicated(),
                "pair_key"
            ]
            .tolist()
        )
        
        raise ValueError(
            f"{fold_id} contains duplicated keys: {duplicate_keys}"
        )
    
    selected_pairs_for_weights_by_fold[fold_id] = weights_input_df

print("Prepared selected-pair tables for weighting:")
print(selected_pairs_for_weights_by_fold.keys())

Prepared selected-pair tables for weighting:
dict_keys(['fold_1', 'fold_2', 'fold_3'])

In [20]:
sample_fold = next(iter(selected_pairs_for_weights_by_fold))

print("Sample fold:", sample_fold)
print("Shape:", selected_pairs_for_weights_by_fold[sample_fold].shape)
print("Columns:", selected_pairs_for_weights_by_fold[sample_fold].columns.tolist())

selected_pairs_for_weights_by_fold[sample_fold][
    ["asset_y", "asset_x", "pair_key"]
].head()

Sample fold: fold_1
Shape: (50, 11)
Columns: ['asset_y', 'asset_x', 'correlation', 'cointegration_pvalue', 'cointegration_passed', 'half_life', 'liquidity_passed', 'avg_dollar_volume_y', 'avg_dollar_volume_x', 'rank', 'pair_key']

  asset_y asset_x   pair_key
0     PEP    COST   PEP_COST
1     UNP    AVGO   UNP_AVGO
2   CMCSA     HON  CMCSA_HON
3   BRK-B      PM   BRK-B_PM
4     JNJ    ABBV   JNJ_ABBV

### 8.3 Construct Weights Across Folds And Methods

This subsection applies each weighting method to each fold-level selected-pair table.

For every fold and weighting method, the selected pairs are converted into normalized portfolio weights. The output is stored in long format so that each row represents one pair, one fold, and one weighting method.

The resulting table will later be validated before being used in the portfolio backtest.

In [21]:
portfolio_weight_records = []

diagnostic_cols = [
    "rank",
    "half_life",
    "correlation",
    "coint_pvalue",
    "avg_dollar_volume_y",
    "avg_dollar_volume_x"
]

for fold_id, selected_pairs_df in selected_pairs_for_weights_by_fold.items():
    for weight_method, weighting_func in WEIGHTING_METHODS.items():

        weights = weighting_func(selected_pairs_df)
        
        if not isinstance(weights, pd.Series):
            weights = pd.Series(weights, index=selected_pairs_df.index)

        if len(weights) != len(selected_pairs_df):
            raise ValueError(
                f"{fold_id} / {weight_method}: weights length does not match selected pairs."
            )
        
        weights = weights.reindex(selected_pairs_df.index)
        
        weights_output_df = selected_pairs_df.copy()
        weights_output_df["fold_id"] = fold_id
        weights_output_df["weight_method"] = weight_method
        weights_output_df["weight"] = weights.values
        
        keep_cols = [
            "fold_id",
            "weight_method",
            "pair_key",
            "asset_y",
            "asset_x",
            "weight"
        ]
        
        keep_cols += [
            col for col in diagnostic_cols
            if col in weights_output_df.columns
        ]

        portfolio_weight_records.append(weights_output_df[keep_cols])

portfolio_weights_df = pd.concat(
    portfolio_weight_records,
    ignore_index=True,
)

print("Portfolio weights shape:", portfolio_weights_df.shape)
portfolio_weights_df.head()

Portfolio weights shape: (372, 11)

,fold_id,weight_method,pair_key,asset_y,asset_x,weight,rank,half_life,correlation,avg_dollar_volume_y,avg_dollar_volume_x
0,fold_1,equal_weight,PEP_COST,PEP,COST,0.02,1,9.566572,0.622783,5.342328e+08,7.227777e+08
1,fold_1,equal_weight,UNP_AVGO,UNP,AVGO,0.02,2,9.769209,0.614099,5.174857e+08,7.066761e+08
2,fold_1,equal_weight,CMCSA_HON,CMCSA,HON,0.02,3,10.033131,0.583763,7.297389e+08,4.687945e+08
3,fold_1,equal_weight,BRK-B_PM,BRK-B,PM,0.02,4,17.274298,0.630418,1.098229e+09,3.200314e+08
4,fold_1,equal_weight,JNJ_ABBV,JNJ,ABBV,0.02,5,13.286042,0.456989,9.272477e+08,5.844794e+08

### 8.4 Validate Portfolio Weights

This subsection validates the portfolio weight table before it is passed into the backtest loop. The goal is to catch allocation errors early, before they contaminate portfolio returns or performance metrics.

In [22]:
validate_portfolio_weights_by_fold(
    portfolio_weights_df=portfolio_weights_df,
    fold_pair_model_artifacts=artifact,
)

Portfolio weight validation passed.

## 9. Run Pair-Level Backtests By Fold

This section runs or loads pair-level backtest results for each selected pair in each fold.

Each pair backtest should use:

- the fold-specific OOS/test period
- the hedge model estimated from the training period
- lagged positions to avoid lookahead bias
- configured entry/exit thresholds
- configured transaction cost assumptions

The result should be a pair-level return series that can be combined into a portfolio.

Lookahead control: positions and signals must use lagged information only. Any hedge ratio, pair selection, or ranking input must come from the training window for that fold.

### 9.1 Run Pair-Level Backtests Across All Walk-Forward Test Folds

In [23]:
cost_scenarios = config["cost_scenarios"]
fold_ids = portfolio_weights_df["fold_id"].unique()

pair_returns_by_scenario = {}
pair_diagnostics_by_scenario = {}
failed_pairs_by_scenario = {}

fold_pair_backtest_summary = []
coverage_checks = []

for scenario_name, cost_config in cost_scenarios.items():

    pair_returns_by_fold = {}
    pair_diagnostics_by_fold = {}
    failed_pairs_by_fold = {}

    for fold_id in fold_ids:

        fold_weights_df = portfolio_weights_df[
            portfolio_weights_df["fold_id"] == fold_id
        ].copy()

        fold_pair_table = fold_weights_df.drop_duplicates("pair_key")
        fold_artifacts = artifact[fold_id]
        fold_test_prices = test_prices_by_fold[fold_id]

        pair_returns_by_pair = {}
        pair_diagnostics = []
        failed_pairs = []

        for _, pair in fold_pair_table.iterrows():

            pair_key = pair["pair_key"]
            asset_y = pair["asset_y"]
            asset_x = pair["asset_x"]

            try:

                hedge_model = fold_artifacts[
                    "hedge_models_by_pair"
                ][pair_key]

                spread_params = fold_artifacts[
                    "spread_params_by_pair"
                ][pair_key]

                test_pair_prices_raw = (
                    fold_test_prices[[asset_y, asset_x]]
                    .dropna()
                )

                test_pair_prices_model = compute_log_prices(
                    test_pair_prices_raw
                )

                test_spread = compute_spread(
                    test_pair_prices_model,
                    hedge_model
                )

                training_mean = spread_params["spread_mean"]
                training_std = spread_params["spread_std"]

                test_zscore = (
                    test_spread - training_mean
                ) / training_std

                common_index = (
                    test_pair_prices_raw.index
                    .intersection(test_zscore.index)
                )

                test_pair_prices_raw = (
                    test_pair_prices_raw.loc[common_index]
                )

                test_zscore = test_zscore.loc[common_index]

                res = run_pair_backtest(
                    price_matrix=test_pair_prices_raw,
                    zscore=test_zscore,
                    hedge_model=hedge_model,
                    entry_threshold=config["backtest"][
                        "entry_threshold"
                    ],
                    exit_threshold=config["backtest"][
                        "exit_threshold"
                    ],
                    min_observations=config["backtest"][
                        "min_observations"
                    ],
                    **cost_config
                )

                pair_return = (
                    res["backtest_df"]["strategy_return"]
                )

                pair_returns_by_pair[pair_key] = pair_return

                pair_diagnostics.append({
                    "scenario": scenario_name,
                    "fold_id": fold_id,
                    "pair_key": pair_key,
                    "asset_y": asset_y,
                    "asset_x": asset_x,
                    "n_obs": len(pair_return),
                    "non_null_returns": pair_return.notna().sum(),
                    "mean_return": pair_return.mean(),
                    "volatility": pair_return.std(),
                    "status": "success"
                })

            except Exception as e:

                failed_pairs.append({
                    "scenario": scenario_name,
                    "fold_id": fold_id,
                    "pair_key": pair_key,
                    "asset_y": asset_y,
                    "asset_x": asset_x,
                    "error_type": type(e).__name__,
                    "error_message": str(e)
                })

        # Build these ONCE after all pairs in the fold
        failed_pairs_df = pd.DataFrame(failed_pairs)
        pair_diagnostics_df = pd.DataFrame(pair_diagnostics)
        pair_returns_df = pd.DataFrame(pair_returns_by_pair)

        pair_returns_by_fold[fold_id] = pair_returns_by_pair
        pair_diagnostics_by_fold[fold_id] = pair_diagnostics_df
        failed_pairs_by_fold[fold_id] = failed_pairs_df

        fold_pair_backtest_summary.append({
            "scenario": scenario_name,
            "fold_id": fold_id,
            "n_pairs_expected": len(fold_pair_table),
            "n_pairs_successful": len(pair_returns_by_pair),
            "n_pairs_failed": len(failed_pairs),
            "pair_returns_shape": pair_returns_df.shape,
            "total_missing_values": (
                pair_returns_df.isna().sum().sum()
                if not pair_returns_df.empty
                else None
            ),
            "start_date": (
                pair_returns_df.index.min()
                if not pair_returns_df.empty
                else None
            ),
            "end_date": (
                pair_returns_df.index.max()
                if not pair_returns_df.empty
                else None
            ),
            "status": (
                "success"
                if len(failed_pairs) == 0
                else "partial"
            )
        })

        # Coverage for THIS scenario + THIS fold
        expected_pair_keys = set(
            fold_weights_df["pair_key"].unique()
        )

        returned_pair_keys = set(
            pair_returns_by_pair.keys()
        )

        missing_pair_keys = (
            expected_pair_keys - returned_pair_keys
        )

        coverage_checks.append({
            "scenario": scenario_name,
            "fold_id": fold_id,
            "expected_pairs": len(expected_pair_keys),
            "returned_pairs": len(returned_pair_keys),
            "missing_pairs": len(missing_pair_keys),
            "status": (
                "success"
                if len(missing_pair_keys) == 0
                else "partial"
            )
        })

    # Save complete scenario
    pair_returns_by_scenario[
        scenario_name
    ] = pair_returns_by_fold

    pair_diagnostics_by_scenario[
        scenario_name
    ] = pair_diagnostics_by_fold

    failed_pairs_by_scenario[
        scenario_name
    ] = failed_pairs_by_fold


fold_pair_backtest_summary_df = pd.DataFrame(
    fold_pair_backtest_summary
)

pair_return_coverage_df = pd.DataFrame(
    coverage_checks
)

pair_return_coverage_df

,scenario,fold_id,expected_pairs,returned_pairs,missing_pairs,status
0,gross,fold_1,50,50,0,success
1,gross,fold_2,50,50,0,success
2,gross,fold_3,24,24,0,success
3,base,fold_1,50,50,0,success
4,base,fold_2,50,50,0,success
5,base,fold_3,24,24,0,success
6,conservative,fold_1,50,50,0,success
7,conservative,fold_2,50,50,0,success
8,conservative,fold_3,24,24,0,success

All walk-forward test folds successfully generated pair-level strategy returns.
Coverage checks confirm that all weighted pair keys have corresponding pair return series.
These outputs will be passed into Section 10 for portfolio construction.

## 10. Aggregate Pair Returns Into Portfolio Returns

This section combines pair-level strategy returns into portfolio-level returns.

For each fold and weighting method:

1. align pair return series by date
2. apply the selected portfolio weights
3. sum weighted pair returns across pairs
4. store the resulting portfolio return series

The output is the main V2 portfolio return artifact.

### 10.1 portfolio returns for all folds using all weighting methods

In [24]:
# Aggregate portfolio returns across all scenarios, folds, and weighting methods

weighted_pair_returns_by_scenario = {}
portfolio_returns_by_scenario = {}
method_diagnostics_by_scenario = {}
failed_method_pairs_by_scenario = {}

portfolio_construction_summary = []

for scenario_name in cost_scenarios:

    pair_returns_by_fold = pair_returns_by_scenario[scenario_name]

    weighted_pair_returns_by_fold_method = {}
    portfolio_returns_by_fold = {}
    method_diagnostics_by_fold = {}
    failed_method_pairs_by_fold = {}

    for fold_id in fold_ids:

        fold_weights_df = portfolio_weights_df[
            portfolio_weights_df["fold_id"] == fold_id
        ].copy()

        pair_returns_by_pair = pair_returns_by_fold[fold_id]
        weight_methods = fold_weights_df["weight_method"].unique()

        weighted_pair_returns_by_method = {}
        portfolio_returns_by_method = {}
        method_diagnostics = []
        failed_method_pairs = []

        for method in weight_methods:

            method_weights_df = fold_weights_df[
                fold_weights_df["weight_method"] == method
            ].copy()

            weighted_returns_this_method = {}
            failed_pairs_this_method = []

            for _, row in method_weights_df.iterrows():

                pair_key = row["pair_key"]
                weight = row["weight"]

                try:
                    pair_return = pair_returns_by_pair[pair_key]
                    weighted_pair_return = pair_return * weight

                    weighted_returns_this_method[pair_key] = weighted_pair_return

                except Exception as e:

                    failure = {
                        "scenario": scenario_name,
                        "fold_id": fold_id,
                        "weight_method": method,
                        "pair_key": pair_key,
                        "weight": weight,
                        "error_type": type(e).__name__,
                        "error_message": str(e)
                    }

                    failed_pairs_this_method.append(failure)
                    failed_method_pairs.append(failure)

            weighted_returns_df = pd.DataFrame(
                weighted_returns_this_method
            )

            portfolio_return = weighted_returns_df.sum(
                axis=1,
                min_count=1
            )

            weighted_pair_returns_by_method[
                method
            ] = weighted_returns_df

            portfolio_returns_by_method[
                method
            ] = portfolio_return

            method_diagnostics.append({
                "scenario": scenario_name,
                "fold_id": fold_id,
                "weight_method": method,
                "n_pairs_expected": len(method_weights_df),
                "n_pairs_used": weighted_returns_df.shape[1],
                "n_failed_pairs": len(failed_pairs_this_method),
                "weight_sum": method_weights_df["weight"].sum(),
                "portfolio_obs": portfolio_return.notna().sum(),
                "portfolio_mean_return": portfolio_return.mean(),
                "portfolio_volatility": portfolio_return.std(),
                "start_date": (
                    portfolio_return.index.min()
                    if not portfolio_return.empty
                    else None
                ),
                "end_date": (
                    portfolio_return.index.max()
                    if not portfolio_return.empty
                    else None
                ),
                "status": (
                    "success"
                    if len(failed_pairs_this_method) == 0
                    else "partial"
                )
            })

        portfolio_returns_df = pd.DataFrame(
            portfolio_returns_by_method
        )

        method_diagnostics_df = pd.DataFrame(
            method_diagnostics
        )

        failed_method_pairs_df = pd.DataFrame(
            failed_method_pairs
        )

        portfolio_returns_by_fold[
            fold_id
        ] = portfolio_returns_df

        weighted_pair_returns_by_fold_method[
            fold_id
        ] = weighted_pair_returns_by_method

        method_diagnostics_by_fold[
            fold_id
        ] = method_diagnostics_df

        failed_method_pairs_by_fold[
            fold_id
        ] = failed_method_pairs_df

        portfolio_construction_summary.append({
            "scenario": scenario_name,
            "fold_id": fold_id,
            "n_methods": len(weight_methods),
            "n_failed_method_pairs": len(failed_method_pairs),
            "portfolio_returns_shape": portfolio_returns_df.shape,
            "start_date": (
                portfolio_returns_df.index.min()
                if not portfolio_returns_df.empty
                else None
            ),
            "end_date": (
                portfolio_returns_df.index.max()
                if not portfolio_returns_df.empty
                else None
            ),
            "status": (
                "success"
                if len(failed_method_pairs) == 0
                else "partial"
            )
        })

    # Save completed scenario
    weighted_pair_returns_by_scenario[
        scenario_name
    ] = weighted_pair_returns_by_fold_method

    portfolio_returns_by_scenario[
        scenario_name
    ] = portfolio_returns_by_fold

    method_diagnostics_by_scenario[
        scenario_name
    ] = method_diagnostics_by_fold

    failed_method_pairs_by_scenario[
        scenario_name
    ] = failed_method_pairs_by_fold


portfolio_construction_summary_df = pd.DataFrame(
    portfolio_construction_summary
)

In [25]:
print("Expected scenarios:", len(cost_scenarios))
print("Completed scenarios:", len(portfolio_returns_by_scenario))

print(
    "Expected scenario-fold runs:",
    len(cost_scenarios) * len(fold_ids)
)

print(
    "Completed scenario-fold runs:",
    len(portfolio_construction_summary_df)
)

for scenario_name in cost_scenarios:
    print(f"\nScenario: {scenario_name}")
    print("Expected folds:", len(fold_ids))
    print(
        "Completed folds:",
        len(portfolio_returns_by_scenario[scenario_name])
    )
    print(
        "Folds with diagnostics:",
        len(method_diagnostics_by_scenario[scenario_name])
    )
    print(
        "Folds with failed method-pair tables:",
        len(failed_method_pairs_by_scenario[scenario_name])
    )

portfolio_construction_summary_df

Expected scenarios: 3
Completed scenarios: 3
Expected scenario-fold runs: 9
Completed scenario-fold runs: 9

Scenario: gross
Expected folds: 3
Completed folds: 3
Folds with diagnostics: 3
Folds with failed method-pair tables: 3

Scenario: base
Expected folds: 3
Completed folds: 3
Folds with diagnostics: 3
Folds with failed method-pair tables: 3

Scenario: conservative
Expected folds: 3
Completed folds: 3
Folds with diagnostics: 3
Folds with failed method-pair tables: 3

,scenario,fold_id,n_methods,n_failed_method_pairs,portfolio_returns_shape,start_date,end_date,status
0,gross,fold_1,3,0,"(250, 3)",2022-01-04 00:00:00+00:00,2022-12-30 00:00:00+00:00,success
1,gross,fold_2,3,0,"(249, 3)",2023-01-04 00:00:00+00:00,2023-12-29 00:00:00+00:00,success
2,gross,fold_3,3,0,"(251, 3)",2024-01-03 00:00:00+00:00,2024-12-31 00:00:00+00:00,success
3,base,fold_1,3,0,"(250, 3)",2022-01-04 00:00:00+00:00,2022-12-30 00:00:00+00:00,success
4,base,fold_2,3,0,"(249, 3)",2023-01-04 00:00:00+00:00,2023-12-29 00:00:00+00:00,success
5,base,fold_3,3,0,"(251, 3)",2024-01-03 00:00:00+00:00,2024-12-31 00:00:00+00:00,success
6,conservative,fold_1,3,0,"(250, 3)",2022-01-04 00:00:00+00:00,2022-12-30 00:00:00+00:00,success
7,conservative,fold_2,3,0,"(249, 3)",2023-01-04 00:00:00+00:00,2023-12-29 00:00:00+00:00,success
8,conservative,fold_3,3,0,"(251, 3)",2024-01-03 00:00:00+00:00,2024-12-31 00:00:00+00:00,success

In [26]:
total_failed_method_pairs = sum(
    len(df)
    for failed_pairs_by_fold in failed_method_pairs_by_scenario.values()
    for df in failed_pairs_by_fold.values()
)

print("Total failed method-pairs:", total_failed_method_pairs)

Total failed method-pairs: 0

In [27]:
sample_scenario = "base"
sample_fold = fold_ids[0]

sample_portfolio_returns = (
    portfolio_returns_by_scenario[sample_scenario][sample_fold]
)

display(sample_portfolio_returns.head())
display(sample_portfolio_returns.describe())

                           equal_weight  rank_weight  inverse_half_life
date
2022-01-04 00:00:00+00:00      0.000000     0.000000           0.000000
2022-01-05 00:00:00+00:00     -0.000712    -0.000220          -0.000588
2022-01-06 00:00:00+00:00      0.001476     0.000532           0.001228
2022-01-07 00:00:00+00:00      0.000711     0.000479           0.000616
2022-01-10 00:00:00+00:00     -0.000511    -0.000522          -0.000432

       equal_weight  rank_weight  inverse_half_life
count    250.000000   250.000000         250.000000
mean      -0.000818    -0.000552          -0.000817
std        0.005652     0.004476           0.005366
min       -0.028707    -0.014657          -0.025955
25%       -0.004091    -0.003167          -0.003849
50%       -0.000595    -0.000526          -0.000608
75%        0.002458     0.002231           0.002333
max        0.017229     0.018829           0.016784

All walk-forward test folds were successfully aggregated into portfolio returns across weighting methods.
Pair-level returns from Section 9 are reused; no pair backtests are recomputed in Section 10.

## 11. Compute Portfolio Performance Metrics

This section computes core performance metrics for each fold and weighting method.

Metrics may include:

- cumulative return
- annualized return
- annualized volatility
- Sharpe ratio
- max drawdown
- hit rate
- average daily return
- Newey-West adjusted t-stat
- turnover and cost totals, if available

Benchmark-aware metrics may be added here if the benchmark return series is already available. Otherwise, they can be computed in Notebook 04.

List of metrics chosen to be computed across all folds and methods:

fold_id
weight_method
start_date
end_date
n_obs
cumulative_return
annualized_return
annualized_volatility
sharpe_ratio
max_drawdown
hit_rate
average_daily_return
daily_return_std
newey_west_t_stat

In [28]:
portfolio_metrics_by_scenario = {}
portfolio_metrics_frames = []

for scenario_name in cost_scenarios:

    portfolio_returns_by_fold = (
        portfolio_returns_by_scenario[scenario_name]
    )

    scenario_metrics_df = summarize_portfolio_by_fold(
        portfolio_returns_by_fold=portfolio_returns_by_fold,
        periods_per_year=252,
        risk_free_rate=0.0,
        newey_west_lags=5,
    )

    scenario_metrics_df["scenario"] = scenario_name

    portfolio_metrics_by_scenario[
        scenario_name
    ] = scenario_metrics_df

    portfolio_metrics_frames.append(
        scenario_metrics_df
    )

portfolio_metrics_df = pd.concat(
    portfolio_metrics_frames,
    ignore_index=True
)

portfolio_metrics_df

,fold_id,weight_method,start_date,end_date,n_observations,final_cumulative_return,mean_daily_return,annualized_return,annualized_volatility,sharpe_ratio,max_drawdown,hit_rate,alpha,annualized_alpha,newey_west_standard_error,newey_west_tstat,newey_west_pvalue,newey_west_lags,scenario
0,fold_1,equal_weight,2022-01-04 00:00:00+00:00,2022-12-30 00:00:00+00:00,250,-0.168286,-0.000721,-0.169511,0.089695,-1.889858,-0.181318,0.436000,-0.000721,-0.181656,0.000354,-2.038537,0.041496,5,gross
1,fold_1,rank_weight,2022-01-04 00:00:00+00:00,2022-12-30 00:00:00+00:00,250,-0.109926,-0.000456,-0.110755,0.071001,-1.559913,-0.144721,0.456000,-0.000456,-0.114845,0.000308,-1.479476,0.139013,5,gross
2,fold_1,inverse_half_life,2022-01-04 00:00:00+00:00,2022-12-30 00:00:00+00:00,250,-0.167930,-0.000721,-0.169153,0.085158,-1.986338,-0.179326,0.436000,-0.000721,-0.181623,0.000342,-2.106419,0.035168,5,gross
3,fold_2,equal_weight,2023-01-04 00:00:00+00:00,2023-12-29 00:00:00+00:00,249,0.053086,0.000223,0.053743,0.088456,0.607564,-0.054672,0.497992,0.000223,0.056238,0.000309,0.722308,0.470105,5,gross
4,fold_2,rank_weight,2023-01-04 00:00:00+00:00,2023-12-29 00:00:00+00:00,249,0.011643,0.000063,0.011784,0.092047,0.128026,-0.063414,0.441767,0.000063,0.015927,0.000307,0.205901,0.836869,5,gross
5,fold_2,inverse_half_life,2023-01-04 00:00:00+00:00,2023-12-29 00:00:00+00:00,249,0.043795,0.000186,0.044334,0.082475,0.537547,-0.058876,0.497992,0.000186,0.046762,0.000292,0.634978,0.525443,5,gross
6,fold_3,equal_weight,2024-01-03 00:00:00+00:00,2024-12-31 00:00:00+00:00,251,-0.043773,-0.000159,-0.043943,0.099040,-0.443695,-0.110286,0.450199,-0.000159,-0.040028,0.000374,-0.424638,0.671100,5,gross
7,fold_3,rank_weight,2024-01-03 00:00:00+00:00,2024-12-31 00:00:00+00:00,251,-0.028576,-0.000088,-0.028688,0.117921,-0.243284,-0.113447,0.498008,-0.000088,-0.022166,0.000436,-0.201809,0.840066,5,gross
8,fold_3,inverse_half_life,2024-01-03 00:00:00+00:00,2024-12-31 00:00:00+00:00,251,-0.034835,-0.000121,-0.034971,0.101739,-0.343737,-0.106459,0.470120,-0.000121,-0.030424,0.000367,-0.329054,0.742115,5,gross
9,fold_1,equal_weight,2022-01-04 00:00:00+00:00,2022-12-30 00:00:00+00:00,250,-0.188279,-0.000818,-0.189633,0.089719,-2.113637,-0.199301,0.428000,-0.000818,-0.206161,0.000354,-2.309544,0.020913,5,base
10,fold_1,rank_weight,2022-01-04 00:00:00+00:00,2022-12-30 00:00:00+00:00,250,-0.131120,-0.000552,-0.132096,0.071053,-1.859112,-0.156581,0.452000,-0.000552,-0.139121,0.000309,-1.786026,0.074095,5,base
11,fold_1,inverse_half_life,2022-01-04 00:00:00+00:00,2022-12-30 00:00:00+00:00,250,-0.187725,-0.000817,-0.189075,0.085189,-2.219491,-0.198253,0.424000,-0.000817,-0.205871,0.000343,-2.382502,0.017195,5,base
12,fold_2,equal_weight,2023-01-04 00:00:00+00:00,2023-12-29 00:00:00+00:00,249,0.023707,0.000110,0.023996,0.088415,0.271399,-0.065082,0.481928,0.000110,0.027595,0.000308,0.355462,0.722243,5,base
13,fold_2,rank_weight,2023-01-04 00:00:00+00:00,2023-12-29 00:00:00+00:00,249,-0.020112,-0.000065,-0.020352,0.092032,-0.221141,-0.087266,0.429719,-0.000065,-0.016351,0.000307,-0.211586,0.832430,5,base
14,fold_2,inverse_half_life,2023-01-04 00:00:00+00:00,2023-12-29 00:00:00+00:00,249,0.014206,0.000070,0.014378,0.082442,0.174402,-0.068939,0.481928,0.000070,0.017653,0.000292,0.240304,0.810094,5,base
15,fold_3,equal_weight,2024-01-03 00:00:00+00:00,2024-12-31 00:00:00+00:00,251,-0.059959,-0.000227,-0.060190,0.099018,-0.607868,-0.114795,0.442231,-0.000227,-0.057165,0.000374,-0.606920,0.543904,5,base
16,fold_3,rank_weight,2024-01-03 00:00:00+00:00,2024-12-31 00:00:00+00:00,251,-0.049478,-0.000175,-0.049670,0.117917,-0.421233,-0.119996,0.482072,-0.000175,-0.044000,0.000436,-0.400570,0.688737,5,base
17,fold_3,inverse_half_life,2024-01-03 00:00:00+00:00,2024-12-31 00:00:00+00:00,251,-0.051408,-0.000190,-0.051608,0.101724,-0.507331,-0.111130,0.466135,-0.000190,-0.047811,0.000367,-0.517383,0.604889,5,base
18,fold_1,equal_weight,2022-01-04 00:00:00+00:00,2022-12-30 00:00:00+00:00,250,-0.207794,-0.000915,-0.209268,0.089744,-2.331825,-0.217941,0.420000,-0.000915,-0.230666,0.000355,-2.579231,0.009902,5,conservative
19,fold_1,rank_weight,2022-01-04 00:00:00+00:00,2022-12-30 00:00:00+00:00,250,-0.151812,-0.000648,-0.152928,0.071111,-2.150559,-0.173296,0.444000,-0.000648,-0.163397,0.000310,-2.089987,0.036619,5,conservative
20,fold_1,inverse_half_life,2022-01-04 00:00:00+00:00,2022-12-30 00:00:00+00:00,250,-0.207051,-0.000913,-0.208522,0.085222,-2.446818,-0.216746,0.412000,-0.000913,-0.230119,0.000344,-2.656953,0.007885,5,conservative
21,fold_2,equal_weight,2023-01-04 00:00:00+00:00,2023-12-29 00:00:00+00:00,249,-0.004857,-0.000004,-0.004915,0.088385,-0.055611,-0.080134,0.469880,-0.000004,-0.001048,0.000307,-0.013527,0.989208,5,conservative
22,fold_2,rank_weight,2023-01-04 00:00:00+00:00,2023-12-29 00:00:00+00:00,249,-0.050876,-0.000193,-0.051473,0.092027,-0.559324,-0.110514,0.413655,-0.000193,-0.048629,0.000307,-0.629336,0.529129,5,conservative
23,fold_2,inverse_half_life,2023-01-04 00:00:00+00:00,2023-12-29 00:00:00+00:00,249,-0.014549,-0.000045,-0.014723,0.082418,-0.178638,-0.083945,0.469880,-0.000045,-0.011456,0.000291,-0.156216,0.875863,5,conservative
24,fold_3,equal_weight,2024-01-03 00:00:00+00:00,2024-12-31 00:00:00+00:00,251,-0.075872,-0.000295,-0.076162,0.098999,-0.769324,-0.119282,0.430279,-0.000295,-0.074303,0.000374,-0.789414,0.429870,5,conservative
25,fold_3,rank_weight,2024-01-03 00:00:00+00:00,2024-12-31 00:00:00+00:00,251,-0.069933,-0.000261,-0.070201,0.117916,-0.595350,-0.126497,0.478088,-0.000261,-0.065835,0.000436,-0.599180,0.549053,5,conservative
26,fold_3,inverse_half_life,2024-01-03 00:00:00+00:00,2024-12-31 00:00:00+00:00,251,-0.067698,-0.000259,-0.067958,0.101710,-0.668157,-0.115802,0.446215,-0.000259,-0.065198,0.000367,-0.705837,0.480290,5,conservative

In [29]:
print(
    portfolio_metrics_df.groupby(
        ["scenario", "weight_method"]
    )[
        [
            "final_cumulative_return",
            "annualized_return",
            "annualized_volatility",
            "sharpe_ratio",
            "max_drawdown",
            "hit_rate",
            "newey_west_tstat",
        ]
    ].agg(["mean", "median", "min", "max"])
)
portfolio_metrics_df.pivot(
    index="fold_id",
    columns=["scenario", "weight_method"],
    values="final_cumulative_return",
)

                               final_cumulative_return                      \
                                                  mean    median       min
scenario     weight_method
base         equal_weight                    -0.074844 -0.059959 -0.188279
             inverse_half_life               -0.074976 -0.051408 -0.187725
             rank_weight                     -0.066903 -0.049478 -0.131120
conservative equal_weight                    -0.096174 -0.075872 -0.207794
             inverse_half_life               -0.096433 -0.067698 -0.207051
             rank_weight                     -0.090873 -0.069933 -0.151812
gross        equal_weight                    -0.052991 -0.043773 -0.168286
             inverse_half_life               -0.052990 -0.034835 -0.167930
             rank_weight                     -0.042286 -0.028576 -0.109926

                                         annualized_return            \
                                     max              mean    median
scenario     weight_method
base         equal_weight       0.023707         -0.075276 -0.060190
             inverse_half_life  0.014206         -0.075435 -0.051608
             rank_weight       -0.020112         -0.067373 -0.049670
conservative equal_weight      -0.004857         -0.096782 -0.076162
             inverse_half_life -0.014549         -0.097068 -0.067958
             rank_weight       -0.050876         -0.091534 -0.070201
gross        equal_weight       0.053086         -0.053237 -0.043943
             inverse_half_life  0.043795         -0.053263 -0.034971
             rank_weight        0.011643         -0.042553 -0.028688

                                                   annualized_volatility  \
                                     min       max                  mean
scenario     weight_method
base         equal_weight      -0.189633  0.023996              0.092384
             inverse_half_life -0.189075  0.014378              0.089785
             rank_weight       -0.132096 -0.020352              0.093667
conservative equal_weight      -0.209268 -0.004915              0.092376
             inverse_half_life -0.208522 -0.014723              0.089783
             rank_weight       -0.152928 -0.051473              0.093684
gross        equal_weight      -0.169511  0.053743              0.092397
             inverse_half_life -0.169153  0.044334              0.089791
             rank_weight       -0.110755  0.011784              0.093656

                                          ... max_drawdown            \
                                  median  ...          min       max
scenario     weight_method                ...
base         equal_weight       0.089719  ...    -0.199301 -0.065082
             inverse_half_life  0.085189  ...    -0.198253 -0.068939
             rank_weight        0.092032  ...    -0.156581 -0.087266
conservative equal_weight       0.089744  ...    -0.217941 -0.080134
             inverse_half_life  0.085222  ...    -0.216746 -0.083945
             rank_weight        0.092027  ...    -0.173296 -0.110514
gross        equal_weight       0.089695  ...    -0.181318 -0.054672
             inverse_half_life  0.085158  ...    -0.179326 -0.058876
             rank_weight        0.092047  ...    -0.144721 -0.063414

                                hit_rate                                \
                                    mean    median       min       max
scenario     weight_method
base         equal_weight       0.450720  0.442231  0.428000  0.481928
             inverse_half_life  0.457354  0.466135  0.424000  0.481928
             rank_weight        0.454597  0.452000  0.429719  0.482072
conservative equal_weight       0.440053  0.430279  0.420000  0.469880
             inverse_half_life  0.442698  0.446215  0.412000  0.469880
             rank_weight        0.445247  0.444000  0.413655  0.478088
gross        equal_weight       0.461397  0.450199  0.436000  0.497992
             inverse_half_life  0.468037  0.470120  0.436000  0.497992
             rank_weight        0.465258  0.456000  0.441767  0.498008

                               newey_west_tstat
                                           mean    median       min       max
scenario     weight_method
base         equal_weight             -0.853667 -0.606920 -2.309544  0.355462
             inverse_half_life        -0.886527 -0.517383 -2.382502  0.240304
             rank_weight              -0.799394 -0.400570 -1.786026 -0.211586
conservative equal_weight             -1.127391 -0.789414 -2.579231 -0.013527
             inverse_half_life        -1.173002 -0.705837 -2.656953 -0.156216
             rank_weight              -1.106168 -0.629336 -2.089987 -0.599180
gross        equal_weight             -0.580289 -0.424638 -2.038537  0.722308
             inverse_half_life        -0.600165 -0.329054 -2.106419  0.634978
             rank_weight              -0.491795 -0.201809 -1.479476  0.205901

[9 rows x 28 columns]

scenario             gross                                       base  \
weight_method equal_weight rank_weight inverse_half_life equal_weight
fold_id
fold_1           -0.168286   -0.109926         -0.167930    -0.188279
fold_2            0.053086    0.011643          0.043795     0.023707
fold_3           -0.043773   -0.028576         -0.034835    -0.059959

scenario                                    conservative              \
weight_method rank_weight inverse_half_life equal_weight rank_weight
fold_id
fold_1          -0.131120         -0.187725    -0.207794   -0.151812
fold_2          -0.020112          0.014206    -0.004857   -0.050876
fold_3          -0.049478         -0.051408    -0.075872   -0.069933

scenario
weight_method inverse_half_life
fold_id
fold_1                -0.207051
fold_2                -0.014549
fold_3                -0.067698

This is the result for the test windows. In section 12, the result for the OOS data will be produced.

## 12. Run OOS Portfolio Backtest

This section repeats the portfolio backtest pipeline on the held-out OOS price data.

No pair selection, hedge model fitting, spread parameter estimation, threshold tuning, or portfolio weight optimization is performed here. The goal is to evaluate whether the training/test-selected portfolio logic survives on a further held-out period.

### 12.1 Validate OOS Inputs:

In [30]:
for fold_id, df in oos_prices_by_fold.items():
    print(fold_id, df.index.min(), df.index.max(), df.shape)

fold_1 2023-01-03 00:00:00+00:00 2023-12-29 00:00:00+00:00 (250, 50)
fold_2 2024-01-02 00:00:00+00:00 2024-12-31 00:00:00+00:00 (252, 50)
fold_3 2025-01-02 00:00:00+00:00 2025-12-31 00:00:00+00:00 (250, 50)

### 12.2 Generate OOS Pair Returns

In [31]:
cost_scenarios = config["cost_scenarios"]
fold_ids = portfolio_weights_df["fold_id"].unique()

oos_pair_returns_by_scenario = {}
oos_pair_diagnostics_by_scenario = {}
oos_failed_pairs_by_scenario = {}

oos_fold_pair_backtest_summary = []
oos_coverage_checks = []

for scenario_name, cost_config in cost_scenarios.items():

    oos_pair_returns_by_fold = {}
    oos_pair_diagnostics_by_fold = {}
    oos_failed_pairs_by_fold = {}

    for fold_id in fold_ids:

        fold_weights_df = portfolio_weights_df[
            portfolio_weights_df["fold_id"] == fold_id
        ].copy()

        fold_pair_table = fold_weights_df.drop_duplicates("pair_key")
        fold_artifacts = artifact[fold_id]
        fold_oos_prices = oos_prices_by_fold[fold_id]

        pair_returns_by_pair = {}
        pair_diagnostics = []
        failed_pairs = []

        for _, pair in fold_pair_table.iterrows():

            pair_key = pair["pair_key"]
            asset_y = pair["asset_y"]
            asset_x = pair["asset_x"]

            try:

                hedge_model = fold_artifacts[
                    "hedge_models_by_pair"
                ][pair_key]

                spread_params = fold_artifacts[
                    "spread_params_by_pair"
                ][pair_key]

                oos_pair_prices_raw = (
                    fold_oos_prices[[asset_y, asset_x]]
                    .dropna()
                )

                oos_pair_prices_model = compute_log_prices(
                    oos_pair_prices_raw
                )

                oos_spread = compute_spread(
                    oos_pair_prices_model,
                    hedge_model
                )

                training_mean = spread_params["spread_mean"]
                training_std = spread_params["spread_std"]

                oos_zscore = (
                    oos_spread - training_mean
                ) / training_std

                common_index = (
                    oos_pair_prices_raw.index
                    .intersection(oos_zscore.index)
                )

                oos_pair_prices_raw = (
                    oos_pair_prices_raw.loc[common_index]
                )

                oos_zscore = oos_zscore.loc[common_index]

                res = run_pair_backtest(
                    price_matrix=oos_pair_prices_raw,
                    zscore=oos_zscore,
                    hedge_model=hedge_model,
                    entry_threshold=config["backtest"][
                        "entry_threshold"
                    ],
                    exit_threshold=config["backtest"][
                        "exit_threshold"
                    ],
                    min_observations=config["backtest"][
                        "min_observations"
                    ],
                    **cost_config
                )

                pair_return = res["backtest_df"]["strategy_return"]

                pair_returns_by_pair[pair_key] = pair_return

                pair_diagnostics.append({
                    "scenario": scenario_name,
                    "fold_id": fold_id,
                    "pair_key": pair_key,
                    "asset_y": asset_y,
                    "asset_x": asset_x,
                    "n_obs": len(pair_return),
                    "non_null_returns": pair_return.notna().sum(),
                    "mean_return": pair_return.mean(),
                    "volatility": pair_return.std(),
                    "status": "success"
                })

            except Exception as e:

                failed_pairs.append({
                    "scenario": scenario_name,
                    "fold_id": fold_id,
                    "pair_key": pair_key,
                    "asset_y": asset_y,
                    "asset_x": asset_x,
                    "error_type": type(e).__name__,
                    "error_message": str(e)
                })

        # Build once after all pairs in this fold
        failed_pairs_df = pd.DataFrame(failed_pairs)
        pair_diagnostics_df = pd.DataFrame(pair_diagnostics)
        pair_returns_df = pd.DataFrame(pair_returns_by_pair)

        oos_pair_returns_by_fold[fold_id] = pair_returns_by_pair
        oos_pair_diagnostics_by_fold[fold_id] = pair_diagnostics_df
        oos_failed_pairs_by_fold[fold_id] = failed_pairs_df

        oos_fold_pair_backtest_summary.append({
            "scenario": scenario_name,
            "fold_id": fold_id,
            "n_pairs_expected": len(fold_pair_table),
            "n_pairs_successful": len(pair_returns_by_pair),
            "n_pairs_failed": len(failed_pairs),
            "pair_returns_shape": pair_returns_df.shape,
            "total_missing_values": (
                pair_returns_df.isna().sum().sum()
                if not pair_returns_df.empty
                else None
            ),
            "start_date": (
                pair_returns_df.index.min()
                if not pair_returns_df.empty
                else None
            ),
            "end_date": (
                pair_returns_df.index.max()
                if not pair_returns_df.empty
                else None
            ),
            "status": (
                "success"
                if len(failed_pairs) == 0
                else "partial"
            )
        })

        # Coverage for this scenario + fold
        expected_pair_keys = set(
            fold_weights_df["pair_key"].unique()
        )

        returned_pair_keys = set(
            pair_returns_by_pair.keys()
        )

        missing_pair_keys = (
            expected_pair_keys - returned_pair_keys
        )

        oos_coverage_checks.append({
            "scenario": scenario_name,
            "fold_id": fold_id,
            "expected_pairs": len(expected_pair_keys),
            "returned_pairs": len(returned_pair_keys),
            "missing_pairs": len(missing_pair_keys),
            "status": (
                "success"
                if len(missing_pair_keys) == 0
                else "partial"
            )
        })

    # Save completed OOS scenario
    oos_pair_returns_by_scenario[
        scenario_name
    ] = oos_pair_returns_by_fold

    oos_pair_diagnostics_by_scenario[
        scenario_name
    ] = oos_pair_diagnostics_by_fold

    oos_failed_pairs_by_scenario[
        scenario_name
    ] = oos_failed_pairs_by_fold


oos_fold_pair_backtest_summary_df = pd.DataFrame(
    oos_fold_pair_backtest_summary
)

oos_pair_return_coverage_df = pd.DataFrame(
    oos_coverage_checks
)

oos_pair_return_coverage_df

,scenario,fold_id,expected_pairs,returned_pairs,missing_pairs,status
0,gross,fold_1,50,50,0,success
1,gross,fold_2,50,50,0,success
2,gross,fold_3,24,24,0,success
3,base,fold_1,50,50,0,success
4,base,fold_2,50,50,0,success
5,base,fold_3,24,24,0,success
6,conservative,fold_1,50,50,0,success
7,conservative,fold_2,50,50,0,success
8,conservative,fold_3,24,24,0,success

### 12.3 Construct OOS Portfolio Returns

In [32]:
# Aggregate OOS portfolio returns across all scenarios, folds, and weighting methods

oos_weighted_pair_returns_by_scenario = {}
oos_portfolio_returns_by_scenario = {}
oos_method_diagnostics_by_scenario = {}
oos_failed_method_pairs_by_scenario = {}

oos_portfolio_construction_summary = []

for scenario_name in cost_scenarios:

    oos_pair_returns_by_fold = oos_pair_returns_by_scenario[scenario_name]

    oos_weighted_pair_returns_by_fold_method = {}
    oos_portfolio_returns_by_fold = {}
    oos_method_diagnostics_by_fold = {}
    oos_failed_method_pairs_by_fold = {}

    for fold_id in fold_ids:

        fold_weights_df = portfolio_weights_df[
            portfolio_weights_df["fold_id"] == fold_id
        ].copy()

        pair_returns_by_pair = oos_pair_returns_by_fold[fold_id]
        weight_methods = fold_weights_df["weight_method"].unique()

        weighted_pair_returns_by_method = {}
        portfolio_returns_by_method = {}
        method_diagnostics = []
        failed_method_pairs = []

        for method in weight_methods:

            method_weights_df = fold_weights_df[
                fold_weights_df["weight_method"] == method
            ].copy()

            weighted_returns_this_method = {}
            failed_pairs_this_method = []

            for _, row in method_weights_df.iterrows():

                pair_key = row["pair_key"]
                weight = row["weight"]

                try:
                    pair_return = pair_returns_by_pair[pair_key]
                    weighted_pair_return = pair_return * weight

                    weighted_returns_this_method[pair_key] = (
                        weighted_pair_return
                    )

                except Exception as e:

                    failure = {
                        "scenario": scenario_name,
                        "fold_id": fold_id,
                        "weight_method": method,
                        "pair_key": pair_key,
                        "weight": weight,
                        "error_type": type(e).__name__,
                        "error_message": str(e),
                    }

                    failed_pairs_this_method.append(failure)
                    failed_method_pairs.append(failure)

            weighted_returns_df = pd.DataFrame(
                weighted_returns_this_method
            )

            portfolio_return = weighted_returns_df.sum(
                axis=1,
                min_count=1
            )

            weighted_pair_returns_by_method[
                method
            ] = weighted_returns_df

            portfolio_returns_by_method[
                method
            ] = portfolio_return

            method_diagnostics.append({
                "scenario": scenario_name,
                "fold_id": fold_id,
                "weight_method": method,
                "n_pairs_expected": len(method_weights_df),
                "n_pairs_used": weighted_returns_df.shape[1],
                "n_failed_pairs": len(failed_pairs_this_method),
                "weight_sum": method_weights_df["weight"].sum(),
                "portfolio_obs": portfolio_return.notna().sum(),
                "portfolio_mean_return": portfolio_return.mean(),
                "portfolio_volatility": portfolio_return.std(),
                "start_date": (
                    portfolio_return.index.min()
                    if not portfolio_return.empty
                    else None
                ),
                "end_date": (
                    portfolio_return.index.max()
                    if not portfolio_return.empty
                    else None
                ),
                "status": (
                    "success"
                    if len(failed_pairs_this_method) == 0
                    else "partial"
                ),
            })

        portfolio_returns_df = pd.DataFrame(
            portfolio_returns_by_method
        )

        method_diagnostics_df = pd.DataFrame(
            method_diagnostics
        )

        failed_method_pairs_df = pd.DataFrame(
            failed_method_pairs
        )

        oos_portfolio_returns_by_fold[
            fold_id
        ] = portfolio_returns_df

        oos_weighted_pair_returns_by_fold_method[
            fold_id
        ] = weighted_pair_returns_by_method

        oos_method_diagnostics_by_fold[
            fold_id
        ] = method_diagnostics_df

        oos_failed_method_pairs_by_fold[
            fold_id
        ] = failed_method_pairs_df

        oos_portfolio_construction_summary.append({
            "scenario": scenario_name,
            "fold_id": fold_id,
            "n_methods": len(weight_methods),
            "n_failed_method_pairs": len(failed_method_pairs),
            "portfolio_returns_shape": portfolio_returns_df.shape,
            "start_date": (
                portfolio_returns_df.index.min()
                if not portfolio_returns_df.empty
                else None
            ),
            "end_date": (
                portfolio_returns_df.index.max()
                if not portfolio_returns_df.empty
                else None
            ),
            "status": (
                "success"
                if len(failed_method_pairs) == 0
                else "partial"
            ),
        })

    # Save completed OOS scenario
    oos_weighted_pair_returns_by_scenario[
        scenario_name
    ] = oos_weighted_pair_returns_by_fold_method

    oos_portfolio_returns_by_scenario[
        scenario_name
    ] = oos_portfolio_returns_by_fold

    oos_method_diagnostics_by_scenario[
        scenario_name
    ] = oos_method_diagnostics_by_fold

    oos_failed_method_pairs_by_scenario[
        scenario_name
    ] = oos_failed_method_pairs_by_fold


oos_portfolio_construction_summary_df = pd.DataFrame(
    oos_portfolio_construction_summary
)

In [33]:
print("Expected scenarios:", len(cost_scenarios))
print("Completed scenarios:", len(oos_portfolio_returns_by_scenario))

print(
    "Expected scenario-fold runs:",
    len(cost_scenarios) * len(fold_ids)
)

print(
    "Completed scenario-fold runs:",
    len(oos_portfolio_construction_summary_df)
)

for scenario_name in cost_scenarios:

    print(f"\nScenario: {scenario_name}")

    print("Expected folds:", len(fold_ids))

    print(
        "Completed folds:",
        len(oos_portfolio_returns_by_scenario[scenario_name])
    )

    print(
        "Folds with diagnostics:",
        len(oos_method_diagnostics_by_scenario[scenario_name])
    )

    print(
        "Folds with failed method-pair tables:",
        len(oos_failed_method_pairs_by_scenario[scenario_name])
    )

oos_portfolio_construction_summary_df

Expected scenarios: 3
Completed scenarios: 3
Expected scenario-fold runs: 9
Completed scenario-fold runs: 9

Scenario: gross
Expected folds: 3
Completed folds: 3
Folds with diagnostics: 3
Folds with failed method-pair tables: 3

Scenario: base
Expected folds: 3
Completed folds: 3
Folds with diagnostics: 3
Folds with failed method-pair tables: 3

Scenario: conservative
Expected folds: 3
Completed folds: 3
Folds with diagnostics: 3
Folds with failed method-pair tables: 3

,scenario,fold_id,n_methods,n_failed_method_pairs,portfolio_returns_shape,start_date,end_date,status
0,gross,fold_1,3,0,"(249, 3)",2023-01-04 00:00:00+00:00,2023-12-29 00:00:00+00:00,success
1,gross,fold_2,3,0,"(251, 3)",2024-01-03 00:00:00+00:00,2024-12-31 00:00:00+00:00,success
2,gross,fold_3,3,0,"(249, 3)",2025-01-03 00:00:00+00:00,2025-12-31 00:00:00+00:00,success
3,base,fold_1,3,0,"(249, 3)",2023-01-04 00:00:00+00:00,2023-12-29 00:00:00+00:00,success
4,base,fold_2,3,0,"(251, 3)",2024-01-03 00:00:00+00:00,2024-12-31 00:00:00+00:00,success
5,base,fold_3,3,0,"(249, 3)",2025-01-03 00:00:00+00:00,2025-12-31 00:00:00+00:00,success
6,conservative,fold_1,3,0,"(249, 3)",2023-01-04 00:00:00+00:00,2023-12-29 00:00:00+00:00,success
7,conservative,fold_2,3,0,"(251, 3)",2024-01-03 00:00:00+00:00,2024-12-31 00:00:00+00:00,success
8,conservative,fold_3,3,0,"(249, 3)",2025-01-03 00:00:00+00:00,2025-12-31 00:00:00+00:00,success

In [34]:
sample_scenario = "base"
sample_fold = fold_ids[0]

sample_oos_portfolio_returns = (
    oos_portfolio_returns_by_scenario[sample_scenario][sample_fold]
)

display(sample_oos_portfolio_returns.head())
display(sample_oos_portfolio_returns.describe())

                           equal_weight  rank_weight  inverse_half_life
date
2023-01-04 00:00:00+00:00      0.000000     0.000000           0.000000
2023-01-05 00:00:00+00:00     -0.004355    -0.004154          -0.004709
2023-01-06 00:00:00+00:00      0.000755     0.003569           0.000637
2023-01-09 00:00:00+00:00      0.014953     0.013267           0.015382
2023-01-10 00:00:00+00:00      0.000971     0.002511           0.000930

       equal_weight  rank_weight  inverse_half_life
count    249.000000   249.000000         249.000000
mean       0.000376     0.000227           0.000317
std        0.005468     0.004845           0.005456
min       -0.013598    -0.015139          -0.015268
25%       -0.002700    -0.002600          -0.002838
50%        0.000297     0.000076           0.000033
75%        0.003159     0.002816           0.003361
max        0.035440     0.025669           0.033907

In [35]:
for scenario_name, portfolio_returns_by_fold in (
    oos_portfolio_returns_by_scenario.items()
):
    print(f"\nScenario: {scenario_name}")

    for fold_id, df in portfolio_returns_by_fold.items():
        print(
            fold_id,
            df.index.min(),
            df.index.max(),
            df.shape
        )

Scenario: gross
fold_1 2023-01-04 00:00:00+00:00 2023-12-29 00:00:00+00:00 (249, 3)
fold_2 2024-01-03 00:00:00+00:00 2024-12-31 00:00:00+00:00 (251, 3)
fold_3 2025-01-03 00:00:00+00:00 2025-12-31 00:00:00+00:00 (249, 3)

Scenario: base
fold_1 2023-01-04 00:00:00+00:00 2023-12-29 00:00:00+00:00 (249, 3)
fold_2 2024-01-03 00:00:00+00:00 2024-12-31 00:00:00+00:00 (251, 3)
fold_3 2025-01-03 00:00:00+00:00 2025-12-31 00:00:00+00:00 (249, 3)

Scenario: conservative
fold_1 2023-01-04 00:00:00+00:00 2023-12-29 00:00:00+00:00 (249, 3)
fold_2 2024-01-03 00:00:00+00:00 2024-12-31 00:00:00+00:00 (251, 3)
fold_3 2025-01-03 00:00:00+00:00 2025-12-31 00:00:00+00:00 (249, 3)

### 12.4 Compute OOS Metrics

In [36]:

oos_portfolio_metrics_by_scenario = {}
oos_portfolio_metrics_frames = []

for scenario_name in cost_scenarios:

    scenario_oos_returns_by_fold = (
        oos_portfolio_returns_by_scenario[scenario_name]
    )

    scenario_metrics_df = summarize_portfolio_by_fold(
        portfolio_returns_by_fold=scenario_oos_returns_by_fold,
        periods_per_year=metric_config["periods_per_year"],
        risk_free_rate=metric_config["risk_free_rate"],
        newey_west_lags=metric_config["newey_west_lags"],
    ).copy()

    scenario_metrics_df["scenario"] = scenario_name

    oos_portfolio_metrics_by_scenario[
        scenario_name
    ] = scenario_metrics_df

    oos_portfolio_metrics_frames.append(
        scenario_metrics_df
    )


oos_portfolio_metrics_df = pd.concat(
    oos_portfolio_metrics_frames,
    ignore_index=True
)

oos_portfolio_metrics_df

,fold_id,weight_method,start_date,end_date,n_observations,final_cumulative_return,mean_daily_return,annualized_return,annualized_volatility,sharpe_ratio,max_drawdown,hit_rate,alpha,annualized_alpha,newey_west_standard_error,newey_west_tstat,newey_west_pvalue,newey_west_lags,scenario
0,fold_1,equal_weight,2023-01-04 00:00:00+00:00,2023-12-29 00:00:00+00:00,249,0.124638,0.000487,0.126230,0.086794,1.108723,-0.044414,0.522088,0.000487,0.122639,0.000320,1.519820,0.128556,5,gross
1,fold_1,rank_weight,2023-01-04 00:00:00+00:00,2023-12-29 00:00:00+00:00,249,0.086721,0.000346,0.087811,0.076911,0.751656,-0.075760,0.510040,0.000346,0.087120,0.000282,1.227412,0.219668,5,gross
2,fold_1,inverse_half_life,2023-01-04 00:00:00+00:00,2023-12-29 00:00:00+00:00,249,0.108485,0.000428,0.109861,0.086598,0.922205,-0.049438,0.514056,0.000428,0.107977,0.000313,1.368215,0.171245,5,gross
3,fold_2,equal_weight,2024-01-03 00:00:00+00:00,2024-12-31 00:00:00+00:00,251,-0.095449,-0.000392,-0.095810,0.060275,-2.087266,-0.113068,0.438247,-0.000392,-0.098884,0.000246,-1.592108,0.111361,5,gross
4,fold_2,rank_weight,2024-01-03 00:00:00+00:00,2024-12-31 00:00:00+00:00,251,-0.117423,-0.000484,-0.117862,0.081619,-1.811613,-0.134202,0.446215,-0.000484,-0.122058,0.000357,-1.355834,0.175152,5,gross
5,fold_2,inverse_half_life,2024-01-03 00:00:00+00:00,2024-12-31 00:00:00+00:00,251,-0.104356,-0.000432,-0.104749,0.059850,-2.251448,-0.117853,0.418327,-0.000432,-0.108843,0.000251,-1.720488,0.085344,5,gross
6,fold_3,equal_weight,2025-01-03 00:00:00+00:00,2025-12-31 00:00:00+00:00,249,-0.064392,-0.000236,-0.065142,0.126263,-0.753520,-0.151808,0.449799,-0.000236,-0.059445,0.000498,-0.474029,0.635479,5,gross
7,fold_3,rank_weight,2025-01-03 00:00:00+00:00,2025-12-31 00:00:00+00:00,249,0.075845,0.000336,0.076793,0.147083,0.318142,-0.086871,0.502008,0.000336,0.084703,0.000563,0.597130,0.550421,5,gross
8,fold_3,inverse_half_life,2025-01-03 00:00:00+00:00,2025-12-31 00:00:00+00:00,249,-0.000884,0.000029,-0.000894,0.129143,-0.239227,-0.099071,0.485944,0.000029,0.007366,0.000513,0.056937,0.954595,5,gross
9,fold_1,equal_weight,2023-01-04 00:00:00+00:00,2023-12-29 00:00:00+00:00,249,0.093970,0.000376,0.095155,0.086807,0.750574,-0.047059,0.514056,0.000376,0.094648,0.000320,1.173483,0.240602,5,base
10,fold_1,rank_weight,2023-01-04 00:00:00+00:00,2023-12-29 00:00:00+00:00,249,0.055075,0.000227,0.055756,0.076920,0.334846,-0.081910,0.506024,0.000227,0.057203,0.000281,0.807112,0.419602,5,base
11,fold_1,inverse_half_life,2023-01-04 00:00:00+00:00,2023-12-29 00:00:00+00:00,249,0.078189,0.000317,0.079168,0.086610,0.567690,-0.055242,0.510040,0.000317,0.079923,0.000313,1.013304,0.310915,5,base
12,fold_2,equal_weight,2024-01-03 00:00:00+00:00,2024-12-31 00:00:00+00:00,251,-0.117802,-0.000492,-0.118243,0.060272,-2.459564,-0.133204,0.426295,-0.000492,-0.123996,0.000247,-1.995397,0.046000,5,base
13,fold_2,rank_weight,2024-01-03 00:00:00+00:00,2024-12-31 00:00:00+00:00,251,-0.146258,-0.000617,-0.146796,0.081607,-2.166427,-0.160967,0.442231,-0.000617,-0.155389,0.000357,-1.727213,0.084129,5,base
14,fold_2,inverse_half_life,2024-01-03 00:00:00+00:00,2024-12-31 00:00:00+00:00,251,-0.128605,-0.000541,-0.129083,0.059843,-2.658357,-0.139865,0.410359,-0.000541,-0.136386,0.000251,-2.155494,0.031123,5,base
15,fold_3,equal_weight,2025-01-03 00:00:00+00:00,2025-12-31 00:00:00+00:00,249,-0.084119,-0.000321,-0.085088,0.126281,-0.911366,-0.164469,0.449799,-0.000321,-0.081002,0.000498,-0.645788,0.518417,5,base
16,fold_3,rank_weight,2025-01-03 00:00:00+00:00,2025-12-31 00:00:00+00:00,249,0.046668,0.000226,0.047243,0.147091,0.117228,-0.095932,0.493976,0.000226,0.056873,0.000563,0.401110,0.688339,5,base
17,fold_3,inverse_half_life,2025-01-03 00:00:00+00:00,2025-12-31 00:00:00+00:00,249,-0.022220,-0.000057,-0.022485,0.129154,-0.406376,-0.112275,0.473896,-0.000057,-0.014478,0.000513,-0.111893,0.910908,5,base
18,fold_1,equal_weight,2023-01-04 00:00:00+00:00,2023-12-29 00:00:00+00:00,249,0.064136,0.000265,0.064933,0.086821,0.402359,-0.052779,0.510040,0.000265,0.066658,0.000320,0.826816,0.408341,5,conservative
19,fold_1,rank_weight,2023-01-04 00:00:00+00:00,2023-12-29 00:00:00+00:00,249,0.024346,0.000108,0.024642,0.076931,-0.069641,-0.088020,0.481928,0.000108,0.027286,0.000281,0.385547,0.699832,5,conservative
20,fold_1,inverse_half_life,2023-01-04 00:00:00+00:00,2023-12-29 00:00:00+00:00,249,0.048718,0.000206,0.049320,0.086624,0.223029,-0.061011,0.493976,0.000206,0.051870,0.000313,0.657988,0.510546,5,conservative
21,fold_2,equal_weight,2024-01-03 00:00:00+00:00,2024-12-31 00:00:00+00:00,251,-0.139606,-0.000592,-0.140121,0.060270,-2.822632,-0.152921,0.414343,-0.000592,-0.149107,0.000247,-2.398121,0.016479,5,conservative
22,fold_2,rank_weight,2024-01-03 00:00:00+00:00,2024-12-31 00:00:00+00:00,251,-0.174156,-0.000749,-0.174785,0.081598,-2.509693,-0.186994,0.430279,-0.000749,-0.188721,0.000357,-2.098988,0.035818,5,conservative
23,fold_2,inverse_half_life,2024-01-03 00:00:00+00:00,2024-12-31 00:00:00+00:00,251,-0.152201,-0.000651,-0.152758,0.059837,-3.054258,-0.161608,0.394422,-0.000651,-0.163930,0.000251,-2.590140,0.009594,5,conservative
24,fold_3,equal_weight,2025-01-03 00:00:00+00:00,2025-12-31 00:00:00+00:00,249,-0.103432,-0.000407,-0.104611,0.126300,-1.065803,-0.177160,0.445783,-0.000407,-0.102560,0.000498,-0.817458,0.413667,5,conservative
25,fold_3,rank_weight,2025-01-03 00:00:00+00:00,2025-12-31 00:00:00+00:00,249,0.018278,0.000115,0.018501,0.147101,-0.078174,-0.104903,0.477912,0.000115,0.029043,0.000562,0.204913,0.837640,5,conservative
26,fold_3,inverse_half_life,2025-01-03 00:00:00+00:00,2025-12-31 00:00:00+00:00,249,-0.043103,-0.000144,-0.043611,0.129166,-0.569894,-0.125287,0.473896,-0.000144,-0.036321,0.000514,-0.280679,0.778957,5,conservative

### 12.5 Compare Test vs OOS Portfolio Metrics

In [37]:
# Compare test and OOS portfolio metrics across
# dataset, cost scenario, fold, and weighting method

comparison_cols = [
    "scenario",
    "fold_id",
    "weight_method",
    "final_cumulative_return",
    "annualized_return",
    "annualized_volatility",
    "sharpe_ratio",
    "max_drawdown",
    "hit_rate",
    "newey_west_tstat",
    "newey_west_pvalue",
]

test_metrics_labelled = portfolio_metrics_df[
    comparison_cols
].copy()

test_metrics_labelled["dataset"] = "test"

oos_metrics_labelled = oos_portfolio_metrics_df[
    comparison_cols
].copy()

oos_metrics_labelled["dataset"] = "oos"

test_oos_metrics_comparison_df = pd.concat(
    [
        test_metrics_labelled,
        oos_metrics_labelled,
    ],
    ignore_index=True,
)

test_oos_metrics_comparison_df = (
    test_oos_metrics_comparison_df
    .sort_values(
        [
            "scenario",
            "fold_id",
            "weight_method",
            "dataset",
        ]
    )
    .reset_index(drop=True)
)

test_oos_metrics_comparison_df

,scenario,fold_id,weight_method,final_cumulative_return,annualized_return,annualized_volatility,sharpe_ratio,max_drawdown,hit_rate,newey_west_tstat,newey_west_pvalue,dataset
0,base,fold_1,equal_weight,0.093970,0.095155,0.086807,0.750574,-0.047059,0.514056,1.173483,0.240602,oos
1,base,fold_1,equal_weight,-0.188279,-0.189633,0.089719,-2.113637,-0.199301,0.428000,-2.309544,0.020913,test
2,base,fold_1,inverse_half_life,0.078189,0.079168,0.086610,0.567690,-0.055242,0.510040,1.013304,0.310915,oos
3,base,fold_1,inverse_half_life,-0.187725,-0.189075,0.085189,-2.219491,-0.198253,0.424000,-2.382502,0.017195,test
4,base,fold_1,rank_weight,0.055075,0.055756,0.076920,0.334846,-0.081910,0.506024,0.807112,0.419602,oos
5,base,fold_1,rank_weight,-0.131120,-0.132096,0.071053,-1.859112,-0.156581,0.452000,-1.786026,0.074095,test
6,base,fold_2,equal_weight,-0.117802,-0.118243,0.060272,-2.459564,-0.133204,0.426295,-1.995397,0.046000,oos
7,base,fold_2,equal_weight,0.023707,0.023996,0.088415,0.271399,-0.065082,0.481928,0.355462,0.722243,test
8,base,fold_2,inverse_half_life,-0.128605,-0.129083,0.059843,-2.658357,-0.139865,0.410359,-2.155494,0.031123,oos
9,base,fold_2,inverse_half_life,0.014206,0.014378,0.082442,0.174402,-0.068939,0.481928,0.240304,0.810094,test
10,base,fold_2,rank_weight,-0.146258,-0.146796,0.081607,-2.166427,-0.160967,0.442231,-1.727213,0.084129,oos
11,base,fold_2,rank_weight,-0.020112,-0.020352,0.092032,-0.221141,-0.087266,0.429719,-0.211586,0.832430,test
12,base,fold_3,equal_weight,-0.084119,-0.085088,0.126281,-0.911366,-0.164469,0.449799,-0.645788,0.518417,oos
13,base,fold_3,equal_weight,-0.059959,-0.060190,0.099018,-0.607868,-0.114795,0.442231,-0.606920,0.543904,test
14,base,fold_3,inverse_half_life,-0.022220,-0.022485,0.129154,-0.406376,-0.112275,0.473896,-0.111893,0.910908,oos
15,base,fold_3,inverse_half_life,-0.051408,-0.051608,0.101724,-0.507331,-0.111130,0.466135,-0.517383,0.604889,test
16,base,fold_3,rank_weight,0.046668,0.047243,0.147091,0.117228,-0.095932,0.493976,0.401110,0.688339,oos
17,base,fold_3,rank_weight,-0.049478,-0.049670,0.117917,-0.421233,-0.119996,0.482072,-0.400570,0.688737,test
18,conservative,fold_1,equal_weight,0.064136,0.064933,0.086821,0.402359,-0.052779,0.510040,0.826816,0.408341,oos
19,conservative,fold_1,equal_weight,-0.207794,-0.209268,0.089744,-2.331825,-0.217941,0.420000,-2.579231,0.009902,test
20,conservative,fold_1,inverse_half_life,0.048718,0.049320,0.086624,0.223029,-0.061011,0.493976,0.657988,0.510546,oos
21,conservative,fold_1,inverse_half_life,-0.207051,-0.208522,0.085222,-2.446818,-0.216746,0.412000,-2.656953,0.007885,test
22,conservative,fold_1,rank_weight,0.024346,0.024642,0.076931,-0.069641,-0.088020,0.481928,0.385547,0.699832,oos
23,conservative,fold_1,rank_weight,-0.151812,-0.152928,0.071111,-2.150559,-0.173296,0.444000,-2.089987,0.036619,test
24,conservative,fold_2,equal_weight,-0.139606,-0.140121,0.060270,-2.822632,-0.152921,0.414343,-2.398121,0.016479,oos
25,conservative,fold_2,equal_weight,-0.004857,-0.004915,0.088385,-0.055611,-0.080134,0.469880,-0.013527,0.989208,test
26,conservative,fold_2,inverse_half_life,-0.152201,-0.152758,0.059837,-3.054258,-0.161608,0.394422,-2.590140,0.009594,oos
27,conservative,fold_2,inverse_half_life,-0.014549,-0.014723,0.082418,-0.178638,-0.083945,0.469880,-0.156216,0.875863,test
28,conservative,fold_2,rank_weight,-0.174156,-0.174785,0.081598,-2.509693,-0.186994,0.430279,-2.098988,0.035818,oos
29,conservative,fold_2,rank_weight,-0.050876,-0.051473,0.092027,-0.559324,-0.110514,0.413655,-0.629336,0.529129,test
30,conservative,fold_3,equal_weight,-0.103432,-0.104611,0.126300,-1.065803,-0.177160,0.445783,-0.817458,0.413667,oos
31,conservative,fold_3,equal_weight,-0.075872,-0.076162,0.098999,-0.769324,-0.119282,0.430279,-0.789414,0.429870,test
32,conservative,fold_3,inverse_half_life,-0.043103,-0.043611,0.129166,-0.569894,-0.125287,0.473896,-0.280679,0.778957,oos
33,conservative,fold_3,inverse_half_life,-0.067698,-0.067958,0.101710,-0.668157,-0.115802,0.446215,-0.705837,0.480290,test
34,conservative,fold_3,rank_weight,0.018278,0.018501,0.147101,-0.078174,-0.104903,0.477912,0.204913,0.837640,oos
35,conservative,fold_3,rank_weight,-0.069933,-0.070201,0.117916,-0.595350,-0.126497,0.478088,-0.599180,0.549053,test
36,gross,fold_1,equal_weight,0.124638,0.126230,0.086794,1.108723,-0.044414,0.522088,1.519820,0.128556,oos
37,gross,fold_1,equal_weight,-0.168286,-0.169511,0.089695,-1.889858,-0.181318,0.436000,-2.038537,0.041496,test
38,gross,fold_1,inverse_half_life,0.108485,0.109861,0.086598,0.922205,-0.049438,0.514056,1.368215,0.171245,oos
39,gross,fold_1,inverse_half_life,-0.167930,-0.169153,0.085158,-1.986338,-0.179326,0.436000,-2.106419,0.035168,test
40,gross,fold_1,rank_weight,0.086721,0.087811,0.076911,0.751656,-0.075760,0.510040,1.227412,0.219668,oos
41,gross,fold_1,rank_weight,-0.109926,-0.110755,0.071001,-1.559913,-0.144721,0.456000,-1.479476,0.139013,test
42,gross,fold_2,equal_weight,-0.095449,-0.095810,0.060275,-2.087266,-0.113068,0.438247,-1.592108,0.111361,oos
43,gross,fold_2,equal_weight,0.053086,0.053743,0.088456,0.607564,-0.054672,0.497992,0.722308,0.470105,test
44,gross,fold_2,inverse_half_life,-0.104356,-0.104749,0.059850,-2.251448,-0.117853,0.418327,-1.720488,0.085344,oos
45,gross,fold_2,inverse_half_life,0.043795,0.044334,0.082475,0.537547,-0.058876,0.497992,0.634978,0.525443,test
46,gross,fold_2,rank_weight,-0.117423,-0.117862,0.081619,-1.811613,-0.134202,0.446215,-1.355834,0.175152,oos
47,gross,fold_2,rank_weight,0.011643,0.011784,0.092047,0.128026,-0.063414,0.441767,0.205901,0.836869,test
48,gross,fold_3,equal_weight,-0.064392,-0.065142,0.126263,-0.753520,-0.151808,0.449799,-0.474029,0.635479,oos
49,gross,fold_3,equal_weight,-0.043773,-0.043943,0.099040,-0.443695,-0.110286,0.450199,-0.424638,0.671100,test
50,gross,fold_3,inverse_half_life,-0.000884,-0.000894,0.129143,-0.239227,-0.099071,0.485944,0.056937,0.954595,oos
51,gross,fold_3,inverse_half_life,-0.034835,-0.034971,0.101739,-0.343737,-0.106459,0.470120,-0.329054,0.742115,test
52,gross,fold_3,rank_weight,0.075845,0.076793,0.147083,0.318142,-0.086871,0.502008,0.597130,0.550421,oos
53,gross,fold_3,rank_weight,-0.028576,-0.028688,0.117921,-0.243284,-0.113447,0.498008,-0.201809,0.840066,test

In [38]:
test_oos_return_pivot_df = (
    test_oos_metrics_comparison_df
    .pivot_table(
        index=["scenario", "fold_id", "weight_method"],
        columns="dataset",
        values="final_cumulative_return",
        aggfunc="first",
    )
    .reset_index()
)

test_oos_return_pivot_df["oos_minus_test"] = (
    test_oos_return_pivot_df["oos"]
    - test_oos_return_pivot_df["test"]
)


test_oos_sharpe_pivot_df = (
    test_oos_metrics_comparison_df
    .pivot_table(
        index=["scenario", "fold_id", "weight_method"],
        columns="dataset",
        values="sharpe_ratio",
        aggfunc="first",
    )
    .reset_index()
)

test_oos_sharpe_pivot_df["oos_minus_test"] = (
    test_oos_sharpe_pivot_df["oos"]
    - test_oos_sharpe_pivot_df["test"]
)


test_oos_drawdown_pivot_df = (
    test_oos_metrics_comparison_df
    .pivot_table(
        index=["scenario", "fold_id", "weight_method"],
        columns="dataset",
        values="max_drawdown",
        aggfunc="first",
    )
    .reset_index()
)

test_oos_drawdown_pivot_df["oos_minus_test"] = (
    test_oos_drawdown_pivot_df["oos"]
    - test_oos_drawdown_pivot_df["test"]
)


test_oos_tstat_pivot_df = (
    test_oos_metrics_comparison_df
    .pivot_table(
        index=["scenario", "fold_id", "weight_method"],
        columns="dataset",
        values="newey_west_tstat",
        aggfunc="first",
    )
    .reset_index()
)

test_oos_tstat_pivot_df["oos_minus_test"] = (
    test_oos_tstat_pivot_df["oos"]
    - test_oos_tstat_pivot_df["test"]
)


summary_metrics = [
    "final_cumulative_return",
    "annualized_return",
    "annualized_volatility",
    "sharpe_ratio",
    "max_drawdown",
    "hit_rate",
    "newey_west_tstat",
]

test_oos_method_summary_df = (
    test_oos_metrics_comparison_df
    .groupby(
        ["dataset", "scenario", "weight_method"]
    )[summary_metrics]
    .agg(["mean", "median", "min", "max"])
)

test_oos_method_summary_df.columns = [
    f"{metric}_{stat}"
    for metric, stat in test_oos_method_summary_df.columns
]

test_oos_method_summary_df = (
    test_oos_method_summary_df
    .reset_index()
)

test_oos_method_summary_df

,dataset,scenario,weight_method,final_cumulative_return_mean,final_cumulative_return_median,final_cumulative_return_min,final_cumulative_return_max,annualized_return_mean,annualized_return_median,annualized_return_min,...,max_drawdown_min,max_drawdown_max,hit_rate_mean,hit_rate_median,hit_rate_min,hit_rate_max,newey_west_tstat_mean,newey_west_tstat_median,newey_west_tstat_min,newey_west_tstat_max
0,oos,base,equal_weight,-0.035984,-0.084119,-0.117802,0.093970,-0.036059,-0.085088,-0.118243,...,-0.164469,-0.047059,0.463383,0.449799,0.426295,0.514056,-0.489234,-0.645788,-1.995397,1.173483
1,oos,base,inverse_half_life,-0.024212,-0.022220,-0.128605,0.078189,-0.024133,-0.022485,-0.129083,...,-0.139865,-0.055242,0.464765,0.473896,0.410359,0.510040,-0.418028,-0.111893,-2.155494,1.013304
2,oos,base,rank_weight,-0.014839,0.046668,-0.146258,0.055075,-0.014599,0.047243,-0.146796,...,-0.160967,-0.081910,0.480744,0.493976,0.442231,0.506024,-0.172997,0.401110,-1.727213,0.807112
3,oos,conservative,equal_weight,-0.059634,-0.103432,-0.139606,0.064136,-0.059933,-0.104611,-0.140121,...,-0.177160,-0.052779,0.456722,0.445783,0.414343,0.510040,-0.796254,-0.817458,-2.398121,0.826816
4,oos,conservative,inverse_half_life,-0.048862,-0.043103,-0.152201,0.048718,-0.049016,-0.043611,-0.152758,...,-0.161608,-0.061011,0.454098,0.473896,0.394422,0.493976,-0.737610,-0.280679,-2.590140,0.657988
5,oos,conservative,rank_weight,-0.043844,0.018278,-0.174156,0.024346,-0.043881,0.018501,-0.174785,...,-0.186994,-0.088020,0.463373,0.477912,0.430279,0.481928,-0.502843,0.204913,-2.098988,0.385547
6,oos,gross,equal_weight,-0.011734,-0.064392,-0.095449,0.124638,-0.011574,-0.065142,-0.095810,...,-0.151808,-0.044414,0.470045,0.449799,0.438247,0.522088,-0.182106,-0.474029,-1.592108,1.519820
7,oos,gross,inverse_half_life,0.001082,-0.000884,-0.104356,0.108485,0.001406,-0.000894,-0.104749,...,-0.117853,-0.049438,0.472776,0.485944,0.418327,0.514056,-0.098445,0.056937,-1.720488,1.368215
8,oos,gross,rank_weight,0.015048,0.075845,-0.117423,0.086721,0.015581,0.076793,-0.117862,...,-0.134202,-0.075760,0.486088,0.502008,0.446215,0.510040,0.156236,0.597130,-1.355834,1.227412
9,test,base,equal_weight,-0.074844,-0.059959,-0.188279,0.023707,-0.075276,-0.060190,-0.189633,...,-0.199301,-0.065082,0.450720,0.442231,0.428000,0.481928,-0.853667,-0.606920,-2.309544,0.355462
10,test,base,inverse_half_life,-0.074976,-0.051408,-0.187725,0.014206,-0.075435,-0.051608,-0.189075,...,-0.198253,-0.068939,0.457354,0.466135,0.424000,0.481928,-0.886527,-0.517383,-2.382502,0.240304
11,test,base,rank_weight,-0.066903,-0.049478,-0.131120,-0.020112,-0.067373,-0.049670,-0.132096,...,-0.156581,-0.087266,0.454597,0.452000,0.429719,0.482072,-0.799394,-0.400570,-1.786026,-0.211586
12,test,conservative,equal_weight,-0.096174,-0.075872,-0.207794,-0.004857,-0.096782,-0.076162,-0.209268,...,-0.217941,-0.080134,0.440053,0.430279,0.420000,0.469880,-1.127391,-0.789414,-2.579231,-0.013527
13,test,conservative,inverse_half_life,-0.096433,-0.067698,-0.207051,-0.014549,-0.097068,-0.067958,-0.208522,...,-0.216746,-0.083945,0.442698,0.446215,0.412000,0.469880,-1.173002,-0.705837,-2.656953,-0.156216
14,test,conservative,rank_weight,-0.090873,-0.069933,-0.151812,-0.050876,-0.091534,-0.070201,-0.152928,...,-0.173296,-0.110514,0.445247,0.444000,0.413655,0.478088,-1.106168,-0.629336,-2.089987,-0.599180
15,test,gross,equal_weight,-0.052991,-0.043773,-0.168286,0.053086,-0.053237,-0.043943,-0.169511,...,-0.181318,-0.054672,0.461397,0.450199,0.436000,0.497992,-0.580289,-0.424638,-2.038537,0.722308
16,test,gross,inverse_half_life,-0.052990,-0.034835,-0.167930,0.043795,-0.053263,-0.034971,-0.169153,...,-0.179326,-0.058876,0.468037,0.470120,0.436000,0.497992,-0.600165,-0.329054,-2.106419,0.634978
17,test,gross,rank_weight,-0.042286,-0.028576,-0.109926,0.011643,-0.042553,-0.028688,-0.110755,...,-0.144721,-0.063414,0.465258,0.456000,0.441767,0.498008,-0.491795,-0.201809,-1.479476,0.205901

In [39]:
print("Return pivot:",test_oos_return_pivot_df.shape)
print("Sharpe pivot:",test_oos_sharpe_pivot_df.shape)
print("Drawdown pivot:",test_oos_drawdown_pivot_df.shape)
print("Newey-West tstat pivot:",test_oos_tstat_pivot_df.shape)
print("Method summary:",test_oos_method_summary_df.shape)

Return pivot: (27, 6)
Sharpe pivot: (27, 6)
Drawdown pivot: (27, 6)
Newey-West tstat pivot: (27, 6)
Method summary: (18, 31)

## 13. Save V2 Portfolio Backtest Outputs

This section saves the structured test and OOS outputs generated by Notebook 03.

Saved outputs should be clean enough for Notebook 04 to load directly without rerunning the full backtest.

The core tables are:

 - portfolio_metrics_df
 - oos_portfolio_metrics_df
 - test_oos_metrics_comparison_df
 - test_oos_return_pivot_df
 - test_oos_sharpe_pivot_df
 - test_oos_drawdown_pivot_df
 - test_oos_tstat_pivot_df
 - test_oos_method_summary_df
 - portfolio_construction_summary_df
 - oos_portfolio_construction_summary_df
 - fold_pair_backtest_summary_df
 - oos_fold_pair_backtest_summary_df
 - pair_return_coverage_df
 - oos_pair_return_coverage_df

Core objects for optional reload:

 - portfolio_returns_by_fold
 - oos_portfolio_returns_by_fold
 - pair_returns_by_fold
 - oos_pair_returns_by_fold

In [40]:
# Ensure output directories exist
TABLES_DIR.mkdir(parents=True, exist_ok=True)
V2_OBJECTS_DIR.mkdir(parents=True, exist_ok=True)


# -----------------------------
# Save scenario-aware CSV tables
# -----------------------------

csv_outputs = {
    "v2_test_portfolio_metrics.csv": portfolio_metrics_df,
    "v2_oos_portfolio_metrics.csv": oos_portfolio_metrics_df,
    "v2_test_oos_metrics_comparison.csv": test_oos_metrics_comparison_df,
    "v2_test_oos_return_pivot.csv": test_oos_return_pivot_df,
    "v2_test_oos_sharpe_pivot.csv": test_oos_sharpe_pivot_df,
    "v2_test_oos_drawdown_pivot.csv": test_oos_drawdown_pivot_df,
    "v2_test_oos_tstat_pivot.csv": test_oos_tstat_pivot_df,
    "v2_test_oos_method_summary.csv": test_oos_method_summary_df,
    "v2_test_portfolio_construction_summary.csv": (
        portfolio_construction_summary_df
    ),
    "v2_oos_portfolio_construction_summary.csv": (
        oos_portfolio_construction_summary_df
    ),
    "v2_test_pair_backtest_summary.csv": (
        fold_pair_backtest_summary_df
    ),
    "v2_oos_pair_backtest_summary.csv": (
        oos_fold_pair_backtest_summary_df
    ),
    "v2_test_pair_return_coverage.csv": pair_return_coverage_df,
    "v2_oos_pair_return_coverage.csv": oos_pair_return_coverage_df,
}

for file_name, dataframe in csv_outputs.items():
    dataframe.to_csv(
        TABLES_DIR / file_name,
        index=False,
    )


# --------------------------------
# Save scenario-aware Python object
# --------------------------------

portfolio_backtest_outputs = {
    "cost_scenarios": cost_scenarios,
    "backtest_config": config["backtest"],
    "metric_config": metric_config,

    "portfolio_returns_by_scenario": (
        portfolio_returns_by_scenario
    ),
    "oos_portfolio_returns_by_scenario": (
        oos_portfolio_returns_by_scenario
    ),

    "pair_returns_by_scenario": pair_returns_by_scenario,
    "oos_pair_returns_by_scenario": (
        oos_pair_returns_by_scenario
    ),

    "portfolio_metrics_df": portfolio_metrics_df,
    "oos_portfolio_metrics_df": oos_portfolio_metrics_df,
    "test_oos_metrics_comparison_df": (
        test_oos_metrics_comparison_df
    ),
}

pickle_file_name = "v2_portfolio_backtest_outputs.pkl"
pickle_output_path = V2_OBJECTS_DIR / pickle_file_name

with open(pickle_output_path, "wb") as file:
    pickle.dump(portfolio_backtest_outputs, file)


# -----------------------------
# Build and validate file manifest
# -----------------------------

saved_outputs = [
    *csv_outputs.keys(),
    pickle_file_name,
]

saved_outputs_df = pd.DataFrame({
    "file_name": saved_outputs,
    "path": [
        str(TABLES_DIR / file_name)
        if file_name.endswith(".csv")
        else str(V2_OBJECTS_DIR / file_name)
        for file_name in saved_outputs
    ],
})

saved_outputs_df["exists"] = (
    saved_outputs_df["path"]
    .map(lambda path: Path(path).exists())
)

display(saved_outputs_df)

print(
    "Files successfully saved:",
    int(saved_outputs_df["exists"].sum()),
    "/",
    len(saved_outputs_df),
)

assert saved_outputs_df["exists"].all(), (
    "One or more expected output files were not created."
)

,file_name,path,exists
0,v2_test_portfolio_metrics.csv,c:\Users\Aditi\Aditi_Workspaces\VSCode\QuantPr...,True
1,v2_oos_portfolio_metrics.csv,c:\Users\Aditi\Aditi_Workspaces\VSCode\QuantPr...,True
2,v2_test_oos_metrics_comparison.csv,c:\Users\Aditi\Aditi_Workspaces\VSCode\QuantPr...,True
3,v2_test_oos_return_pivot.csv,c:\Users\Aditi\Aditi_Workspaces\VSCode\QuantPr...,True
4,v2_test_oos_sharpe_pivot.csv,c:\Users\Aditi\Aditi_Workspaces\VSCode\QuantPr...,True
5,v2_test_oos_drawdown_pivot.csv,c:\Users\Aditi\Aditi_Workspaces\VSCode\QuantPr...,True
6,v2_test_oos_tstat_pivot.csv,c:\Users\Aditi\Aditi_Workspaces\VSCode\QuantPr...,True
7,v2_test_oos_method_summary.csv,c:\Users\Aditi\Aditi_Workspaces\VSCode\QuantPr...,True
8,v2_test_portfolio_construction_summary.csv,c:\Users\Aditi\Aditi_Workspaces\VSCode\QuantPr...,True
9,v2_oos_portfolio_construction_summary.csv,c:\Users\Aditi\Aditi_Workspaces\VSCode\QuantPr...,True
10,v2_test_pair_backtest_summary.csv,c:\Users\Aditi\Aditi_Workspaces\VSCode\QuantPr...,True
11,v2_oos_pair_backtest_summary.csv,c:\Users\Aditi\Aditi_Workspaces\VSCode\QuantPr...,True
12,v2_test_pair_return_coverage.csv,c:\Users\Aditi\Aditi_Workspaces\VSCode\QuantPr...,True
13,v2_oos_pair_return_coverage.csv,c:\Users\Aditi\Aditi_Workspaces\VSCode\QuantPr...,True
14,v2_portfolio_backtest_outputs.pkl,c:\Users\Aditi\Aditi_Workspaces\VSCode\QuantPr...,True

Files successfully saved: 15 / 15

## 14. Notebook 03 Summary

This notebook constructed and evaluated V2 portfolio-level backtests using fold-level selected pairs from the walk-forward pipeline.

The main outputs are:

- portfolio weights by fold and method
- pair-level backtest returns
- portfolio-level returns
- portfolio performance metrics
- metadata describing assumptions and configuration

Notebook 04 will use these outputs to compare weighting methods, cost assumptions, benchmark relationships, and overall research conclusions.